#!/bin/sh

PREREQ=""

prereqs() {
   echo "${PREREQ}"
}

case ${1} in
   prereqs)
      prereqs
      exit 0
      ;;
esac

if [ "${sdmem}" ] ; then
   /usr/bin/sdmem -vllf
fi

case "${sdmem}" in
   halt)
      /sbin/halt -fndp
      ;;
   reboot)
      /sbin/reboot -fnd
      ;;
   *)
      ;;
esac
