#!/bin/sh

PREREQ=""

prereqs() {
   echo "${PREREQ}"
}

tweak_sysctl() {
   echo 3   > /proc/sys/kernel/printk

   echo 3   > /proc/sys/vm/drop_caches
   echo 256 > /proc/sys/vm/min_free_kbytes

   echo 1   > /proc/sys/vm/overcommit_memory
   echo 1   > /proc/sys/vm/oom_kill_allocating_task
   echo 0   > /proc/sys/vm/oom_dump_tasks
}

case ${1} in
   prereqs)
      prereqs
      exit 0
      ;;
esac

if [ -n "${sdmem}" ] ; then
   tweak_sysctl
   if [ -n "${sdmemopts}" ] ; then
      for i in $(seq 0 31) ; do /usr/bin/sdmem "-${sdmemopts}" & done
   else
      for i in $(seq 0 31) ; do /usr/bin/sdmem -v & done
   fi
fi

case "${sdmem}" in
   halt)
      /sbin/halt -fndp
      ;;
   reboot)
      /sbin/reboot -fnd
      ;;
   *)
      ;;
esac
