#!/bin/sh

set -e

prereqs() {
	echo "${PREREQ}"
}

case "$1" in
   prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions

manual_add_modules nouveau

# According to <http://www.phoronix.com/scan.php?page=news_item&px=MTAxOTk>,
# this will be relevant when VirtualBox 4.2 is released.
#manual_add_modules vboxvideo
