#!/bin/sh

set -e

# FIXME: what is this used for? dependency-based hooks ordering?
PREREQ=""

prereqs() {
   echo "${PREREQ}"
}

case "${1}" in
   prereqs)
      prereqs
      exit 0
      ;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /sbin/halt
copy_exec /sbin/reboot
copy_exec /usr/bin/sdmem
copy_exec /usr/bin/seq
