#!/bin/bash

set -e

# Including common functions
. "${LB_BASE:-/usr/share/live/build}"/scripts/build.sh

# Setting static variables
DESCRIPTION="$(Echo 'renaming kernels')"
HELP=""
USAGE="${PROGRAM}"

# Reading configuration files
Read_conffiles config/all config/common config/binary
Set_defaults

Echo_message "Renaming kernels"

mv binary/live/vmlinuz-*-686 binary/live/vmlinuz
mv binary/live/initrd.img-*-686 binary/live/initrd.img
mv binary/live/vmlinuz-*-amd64 binary/live/vmlinuz2
mv binary/live/initrd.img-*-amd64 binary/live/initrd2.img
