#!/bin/bash

# Including common functions
. "${LH_BASE:-/usr/share/live-helper}"/live-helper.sh

# Setting static variables
DESCRIPTION="$(Echo 'removing buggy syslinux help')"
HELP=""
USAGE="${PROGRAM}"

# Reading configuration files
Read_conffiles config/all config/common config/binary
Set_defaults

if [ "${LH_BOOTLOADER}" != "syslinux" ]
then
	exit 0
fi

Echo_message "removing buggy syslinux help"

# Setting boot method specific variables
case "${LH_BINARY_IMAGES}" in
	iso|iso-hybrid)
		SYSLINUX_PATH="binary/isolinux"
		;;
	usb-hdd)
		SYSLINUX_PATH="binary/syslinux"
		;;
esac

# Remove help menu entry from menu.cfg
CFG_FILE="${SYSLINUX_PATH}/menu.cfg"
ORIG_CFG_FILE="${CFG_FILE}.orig"
mv "${CFG_FILE}" "${ORIG_CFG_FILE}"
HELP_START="`grep --color=never --line-number --max-count=1 '^label help$' "${ORIG_CFG_FILE}" | awk -F':' '{print $1}'`"
KEEP_LINES="$(($HELP_START - 1))"
head -n "$KEEP_LINES" "${ORIG_CFG_FILE}" > "${CFG_FILE}"
rm -f "${ORIG_CFG_FILE}"
