#!/bin/bash

# Including common functions
. "${LH_BASE:-/usr/share/live-helper}"/live-helper.sh

# Setting static variables
DESCRIPTION="$(Echo 'internationalizing the syslinux menu')"
HELP=""
USAGE="${PROGRAM}"

# Reading configuration files
Read_conffiles config/all config/common config/binary
Set_defaults

if [ "${LH_BOOTLOADER}" != "syslinux" ]
then
	exit 0
fi

Echo_message "internationalizing the syslinux menu"

# Get AMNESIA_SUPPORTED_LANGUAGES
. config/amnesia
if [ -e config/amnesia.local ] ; then
   . config/amnesia.local
fi

# Setting boot method specific variables
case "${LH_BINARY_IMAGES}" in
	iso)
		SYSLINUX_PATH="binary/isolinux"
		;;
	usb-hdd)
		SYSLINUX_PATH="binary/syslinux"
		;;
esac

# Setting variables
SYSLINUX_LIVE_CFG="${SYSLINUX_PATH}/live.cfg"
ORIG_SYSLINUX_LIVE_CFG="${SYSLINUX_PATH}/live.cfg.orig"
CFG_SNIPPET="${SYSLINUX_PATH}/tmp.cfg"

# Backup the original live.cfg
mv "${SYSLINUX_LIVE_CFG}" "${ORIG_SYSLINUX_LIVE_CFG}"

# Get needed values from the original live.cfg
ORIG_KERNEL="`grep -E --max-count=1 '^[ 	]+kernel ' "${ORIG_SYSLINUX_LIVE_CFG}"`"
ORIG_APPEND="`grep -E --max-count=1 '^[ 	]+append ' "${ORIG_SYSLINUX_LIVE_CFG}"`"

# Sanity checks
if [ -z "${ORIG_KERNEL}" ]; then
   Echo_error "Could not parse kernel line in ${ORIG_SYSLINUX_LIVE_CFG}"
   exit 15
fi
if [ -z "${ORIG_APPEND}" ]; then
   Echo_error "Could not parse append line in ${ORIG_SYSLINUX_LIVE_CFG}"
   exit 16
fi

# Add menu entries
for LANG_CODE in ${AMNESIA_SUPPORTED_LANGUAGES}; do

   case "${LANG_CODE}" in
      ar)
	 LANG_NAME='^Arabic'
	 LANG_APPEND='locale=ar' # FIXME: probably suboptimal
	 ;;
      de)
	 LANG_NAME='^German'
	 LANG_APPEND='locale=de_DE.UTF-8 keyb=de timezone=Europe/Berlin'
	 ;;
      en)
	 LANG_NAME='^English'
	 LANG_APPEND='locale=en_US.UTF-8 keyb=us timezone=America/Detroit'
	 ;;
      es)
	 LANG_NAME='^Spanish'
	 LANG_APPEND='locale=es keyb=es'
	 ;;
      fr)
	 LANG_NAME='^French'
	 LANG_APPEND='locale=fr_FR.UTF-8 keyb=fr timezone=Europe/Paris'
	 ;;
      it)
	 LANG_NAME='^Italian'
	 LANG_APPEND='locale=it'
	 ;;
      pt)
	 LANG_NAME='^Portuguese'
	 LANG_APPEND='locale=pt'
	 ;;
      ru)
	 LANG_NAME='^Russian'
	 LANG_APPEND='locale=ru'
	 ;;
      zh)
	 LANG_NAME='^Chinese'
	 LANG_APPEND='locale=zh_CN.UTF-8 keyb=zh'
	 ;;
      *)
	 Echo_error "Language ${LANG_CODE} is not supported yet, ask amnesia developpers!"
	 exit 17
	 ;;
   esac

   echo "label amnesia-${LANG_CODE}" >> "${CFG_SNIPPET}"
   echo "	menu label ${LANG_NAME}" >> "${CFG_SNIPPET}"
   if [ "${LANG_CODE}" = 'en' ]; then
      echo '	menu default' >> "${CFG_SNIPPET}"
   fi
   echo "${ORIG_KERNEL}" >> "${CFG_SNIPPET}"
   echo "${ORIG_APPEND} ${LANG_APPEND}" >> "${CFG_SNIPPET}"
   cat "${CFG_SNIPPET}" >> "${SYSLINUX_LIVE_CFG}"

   rm -f "${CFG_SNIPPET}"

done

# Cleanup
rm -f "${ORIG_SYSLINUX_LIVE_CFG}"
