#!/bin/bash

set -e

# Including common functions
. "${LB_BASE:-/usr/share/live/build}"/scripts/build.sh

# Setting static variables
DESCRIPTION="$(Echo 'installing syslinux UEFI bootloader')"
HELP=""
USAGE="${PROGRAM}"

# Reading configuration files
Read_conffiles config/all config/bootstrap config/common config/binary
Set_defaults

# Safeguards
[ "${LB_BOOTLOADER}"   = "syslinux" ] || exit 0
[ "${LB_ARCHITECTURE}" = "i386"     ] || exit 0

# Seems like we'll have work to do
Echo_message "installing syslinux UEFI bootloader"

# Setting boot method specific variables
case "${LB_BINARY_IMAGES}" in
	iso|iso-hybrid)
		SYSLINUX_PATH="binary/isolinux"
		;;
	usb-hdd)
		SYSLINUX_PATH="binary/syslinux"
		;;
esac

### Main

## 64-bit
for bit in 32 64 ; do
	case "$bit" in
		32)
			TARGET_SUBDIR=TAILS32
			BOOTLOADER_NAME=bootia32
			SYSLINUX_SUBDIR=efi32
			;;
		64)
			TARGET_SUBDIR=BOOT
			BOOTLOADER_NAME=bootx64
			SYSLINUX_SUBDIR=efi64
			;;
	esac
	TARGET_DIR="binary/EFI/${TARGET_SUBDIR}"
	mkdir -p "${TARGET_DIR}"
	cp "chroot/usr/lib/SYSLINUX.EFI/${SYSLINUX_SUBDIR}/syslinux.efi" \
		"${TARGET_DIR}/${BOOTLOADER_NAME}.efi"
	cp chroot/usr/share/tails/bootx64.png \
		"${TARGET_DIR}/${BOOTLOADER_NAME}.png"
	cp "$SYSLINUX_PATH"/* "${TARGET_DIR}"
	cp -f "chroot/usr/lib/syslinux/modules/${SYSLINUX_SUBDIR}/"* \
		"${TARGET_DIR}"
	sed -r -i -e 's,^(menu background splash\.png)$,\#\1,' \
	    "${TARGET_DIR}/stdmenu.cfg"
done
