#! /bin/sh

xgettext --language=Perl \
   -o config/chroot_local-includes/usr/share/amnesia-security-check/messages.pot \
   config/chroot_local-includes/usr/local/bin/amnesia-security-check

msgmerge -U \
   config/chroot_local-includes/usr/share/amnesia-security-check/messages.pot \
   config/chroot_local-includes/usr/share/locale/fr/LC_MESSAGES/amnesia-security-check.po

msgfmt \
   -o config/chroot_local-includes/usr/share/locale/fr/LC_MESSAGES/amnesia-security-check.mo \
   config/chroot_local-includes/usr/share/locale/fr/LC_MESSAGES/amnesia-security-check.po
