#!/bin/sh

set -e
set -u

. /usr/local/lib/tails-shell-library/tails-greeter.sh

BOOKMARKS_FILE="${HOME}/.config/gtk-3.0/bookmarks"

add_gtk_bookmark_for() {
   local target
   target=$(echo "$1" | sed 's, ,%20,g')

   if [ $# -ge 2 ]; then
      title="$2"
      echo "file://$target $title" >> "${BOOKMARKS_FILE}"
   else
       echo "file://$target" >> "${BOOKMARKS_FILE}"
   fi
}

mkdir -p $(dirname "${BOOKMARKS_FILE}")

add_gtk_bookmark_for "${HOME}/Tor Browser"

if persistence_is_enabled_for "${HOME}/Persistent" ; then
    add_gtk_bookmark_for "${HOME}/Persistent"

    if persistence_is_enabled_read_write ; then
	add_gtk_bookmark_for "${HOME}/Persistent/Tor Browser" \
                             "Tor Browser (persistent)"
    fi
fi

for launcher in Report_an_error tails-documentation ; do
    gio set "${HOME}/Desktop/${launcher}.desktop" metadata::trusted true
done
