#!/bin/sh

set -eu

USAGE="Usage: $(basename $0) on|off"

print_usage_and_exit () {
   echo "$USAGE" >&2
   exit 1
}

[ $# -eq 1 ] || print_usage_and_exit

case "$1" in
   on)
      perl -p -i \
	   -E 's,\A ((?:\#)? \s* deb(?:-src)? \s+)http://,$1tor+http://,xms' \
	   /etc/apt/sources.list /etc/apt/sources.list.d/*.list
      ;;
   off)
      perl -p -i \
	   -E 's,\A ((?:\#)? \s* deb(?:-src)? \s+)tor[+]http://,$1http://,xms' \
	   /etc/apt/sources.list /etc/apt/sources.list.d/*.list
      ;;
   *)
      print_usage_and_exit
      ;;
esac
