#!/bin/sh

set -e
set -u

# Import the TBB_PROFILE variable
. /usr/local/lib/tails-shell-library/tor-browser.sh

USER_PROFILE="${HOME}/.tor-browser"

if [ -e "${USER_PROFILE}" ]; then
    echo "A tor-browser profile already exists at: ${USER_PROFILE}" >&2
    exit 1
fi

mkdir -p "${USER_PROFILE}"
cp -a "${TBB_PROFILE}" "${USER_PROFILE}"/profile.default
