#! /usr/bin/env python3
"""
Tails' seahorse-tool wrapper

Due to this bug:

    https://gitlab.gnome.org/GNOME/seahorse/-/issues/236

Tails users experience problems when using the GNOME Files integration
of Seahorse to import keys. Basically, `seahorse-tool --import` is
broken for binary (non-armored) keys, so we wrap around it and handle
that situation with `gpg --import`.

"""

import gi
import os
import os.path
import sh
import subprocess
import sys
from gettext import gettext
gi.require_version('Notify', '0.7')
from gi.repository import Notify

os.environ['TEXTDOMAIN'] = 'tails'


def notify(message):
    title = gettext("Keys Imported")
    Notify.init(title)
    n = Notify.Notification.new(title, message)
    n.show()


def gpg_import(key_path):
    key_name = os.path.basename(key_path)
    try:
        subprocess.run(['/usr/bin/gpg', '--import', key_path],
                       check=True, capture_output=True)
    except subprocess.CalledProcessError as e:
        notify(gettext("Failed to import keys from {key}:\n{error}")
               .format(key=key_name, error=e.stderr.decode()))
        sys.exit(e.returncode)
    notify(gettext("Imported keys from {key}").format(key=key_name))


if __name__ == '__main__':
    if len(sys.argv) == 3 and sys.argv[1] == '--import':
        gpg_import(sys.argv[2])
    else:
        os.execv('/usr/lib/seahorse/seahorse-tool',
                 ['/usr/lib/seahorse/seahorse-tool'] + sys.argv[1:])
