#! /usr/bin/env python3
"""
Tails' seahorse-tool wrapper

Due to this bug:

    https://gitlab.gnome.org/GNOME/seahorse/-/issues/236

Tails users experience problems when using the GNOME Files integration
of Seahorse to import keys. Basically, `seahorse-tool --import` is
broken for binary (non-armored) keys, so we wrap around it and handle
that situation with `gpg --import`.

"""

import gettext
import gi
import gnupg
import os
import os.path
import subprocess
import sys
gi.require_version('Notify', '0.7')
from gi.repository import Notify

tr = gettext.translation("tails", '/usr/share/locale', fallback=True)


def notify(title, message):
    Notify.init(title)
    n = Notify.Notification.new(title, message)
    n.show()


if __name__ == '__main__':
    if len(sys.argv) == 3 and sys.argv[1] == '--import':
        key_path = sys.argv[2]
        try:
            subprocess.run(['/usr/bin/gpg', '--import', key_path],
                           check=True, capture_output=True)
        except subprocess.CalledProcessError as e:
            notify(tr.gettext("Import Failed"),
                   # Translators: Don't translate {path} or {error},
                   # they are placeholders and will be replaced.
                   # They need to be present in the translated string.
                   tr.gettext("Failed to import keys from {path}:\n{error}")
                   .format(path=key_path, error=e.stderr.decode()))
            sys.exit(e.returncode)
        keys = gnupg.GPG().scan_keys(key_path)
        uids = set()
        for key in keys:
            for uid in key['uids']:
                uids.add(uid)
        title = tr.ngettext("Key Imported", "Keys Imported", len(keys))
        # Translators: Don't translate {uids}, it's a placeholder and
        # will be replaced. It needs to be present in the translated string.
        message = tr.ngettext("Imported a key for {uids}",
                              "Imported keys for {uids}",
                              len(keys)) \
                  .format(uids=", ".join(uids))
        notify(title, message)
    else:
        os.execv('/usr/lib/seahorse/seahorse-tool',
                 ['/usr/lib/seahorse/seahorse-tool'] + sys.argv[1:])
