#!/usr/bin/env python

import locale
import os
import subprocess
import sys

from gettext import gettext as _
from gettext import bindtextdomain, textdomain

from gi.repository import Gdk
from gi.repository import Gtk
from gi.repository import PanelApplet

LOCALE_PREFIX = "%susr" % (os.sep)
LOCALE_DIR = "%s%sshare%slocale" % ( LOCALE_PREFIX, os.sep, os.sep )
PACKAGE = "shutdown_helper_applet"
TEXT_DOMAIN = "tails"
locale.setlocale(locale.LC_ALL, "")
bindtextdomain(PACKAGE, LOCALE_DIR)
textdomain(TEXT_DOMAIN)

def applet_factory(applet, iid, data=None):
    image = Gtk.Image()
    image.set_from_file('/usr/share/icons/gnome/scalable/actions/system-shutdown-symbolic.svg')
    applet.add(image)
    applet.connect('button-press-event', show_action_menu)
    applet.show_all()
    return True

def show_action_menu(applet, event):
    if event.button != Gdk.BUTTON_PRIMARY:
        return

    menu = Gtk.Menu()
    menu.attach_to_widget(applet, None)
    menu_entries = [
#                   [_("Lock Screen"),          'gnome-lockscreen', lock_screen],
                   [_("Shutdown Immediately"), 'gnome-shutdown',   shutdown],
                   [_("Reboot Immediately"),   'gtk-refresh',      reboot]
                  ]
    for [label, icon_name, action] in menu_entries:
        item = Gtk.ImageMenuItem.new_with_label(label)
        icon = Gtk.Image()
        icon.set_from_icon_name(icon_name, Gtk.IconSize.MENU)
        item.set_image(icon)
        item.connect("activate", action)
        item.show()
        menu.add(item)
    menu.popup(parent_menu_shell=None,
               parent_menu_item=None,
               func=None,
               data=None,
               button=event.button,
               activate_time=event.time)

def lock_screen(widget):
    subprocess.call(["gnome-screensaver-command", "--lock"])

def shutdown(widget):
    subprocess.call(["sudo", "-n", "halt"])

def reboot(widget):
    subprocess.call(["sudo", "-n", "reboot"])

# run it in a gtk window
if len(sys.argv) > 1 and sys.argv[1] == "test":
    main_window = Gtk.Window(Gtk.WindowType.TOPLEVEL)
    main_window.set_title("Shutdown Helper")
    main_window.connect("destroy", Gtk.main_quit)
    applet_factory(main_window, None)
    main_window.show_all()
    Gtk.main()
    sys.exit()

if __name__ == '__main__':
    PanelApplet.Applet.factory_main("ShutdownHelperFactory",
        PanelApplet.Applet.__gtype__,
        applet_factory,
        None)
