#!/usr/bin/python3
"""
Allows running systemctl as a different user
"""

import sys
import os
from tailslib.gnome import gnome_env_vars


def main():
    user = sys.argv[1]
    cmd_args = sys.argv[2:]
    if cmd_args[0] == "--":
        cmd_args = cmd_args[1:]

    runuser = ["runuser", "-u", user, "--"]
    env = ["env", *gnome_env_vars()]
    cmd = [*runuser, *env, *cmd_args]
    os.execvp(cmd[0], cmd)


if __name__ == "__main__":
    main()
