#!/bin/sh

journalctl --unit=NetworkManager.service --output=json-pretty --follow \
    | jq --monochrome-output --unbuffered --raw-output '.MESSAGE'      \
    | /usr/local/sbin/tails-restricted-network-detector
