#!/usr/bin/perl

use strict;
use warnings;

#man{{{

=head1 NAME

tails-i2p-removal-notify-user

=head1 VERSION

Version X.XX

=head1 AUTHOR

Tails dev team <amnesia@boum.org>
See https://tails.boum.org/.

=cut

#}}}

use Desktop::Notify;
use English '-no_match_vars';
use Locale::gettext;
use Net::DBus::Reactor;
use POSIX;

### initialization
setlocale(LC_MESSAGES, "");
textdomain("tails");

### callbacks

sub action_cb {
    my $reactor = shift;
    unless (fork) {
        exec(
            '/usr/local/bin/tails-documentation',
            'doc/anonymous_internet/i2p',
            'removal',
        );
    }
    $reactor->shutdown;
}

### main

my $reactor = Net::DBus::Reactor->main;

my $notify  = Desktop::Notify->new();
$notify->action_callback(sub { action_cb($reactor, @_) });
$notify->close_callback(sub { $reactor->shutdown; });

my $summary = gettext("Warning: I2P will be removed in Tails 2.12");
$notify->create(summary => $summary,
                actions => { "moreinfo_$PID" => gettext('Learn more'), },
                hints   => { 'transient' => 1, },
                timeout => 0)->show();

$reactor->run;
