#!/usr/bin/python3

# Tor control port filter proxy, only white-listing SIGNAL NEWNYM,
# ADD_ONION, and DEL_ONION.

# This filter proxy should allow Torbutton to request a
# new Tor circuit, without exposing dangerous control requests
# like "GETINFO address" to applications running as a local user.

# If something goes wrong, an error code is returned, and
# Torbutton will display a warning dialog that New Identity failed.

# This filter proxy also allows software like OnionShare or Ricochet
# to add and delete ephermeral hidden services.

import socketserver
import re
import psutil
import yaml
import glob

from stem.control import Controller, EventType
from stem import SocketError

# Limit the length of a line, to prevent DoS attacks trying to
# crash this filter proxy by sending infinitely long lines.
MAX_LINESIZE = 128

class UnexpectedAnswer(Exception):
    def __init__(self, msg):
        self.msg = msg
    def __str__(self):
        return "[UnexpectedAnswer] " + self.msg

def handle_controlport_session(controller, readh, writeh, allowed_commands, allowed_events):
    def respond(line, raw = False):
        writeh.write(bytes(line, 'ascii'))
        if not raw: writeh.write(bytes("\r\n", 'ascii'))
        writeh.flush()

    subscribed_event_listeners = []

    while True:
        line = str(readh.readline(MAX_LINESIZE), 'ascii').strip()

        if not line: break

        def line_matches_command(cmd):
            # The control port language does not care about case for
            # commands.
            return re.match(r"^%s\b" % cmd, line, re.IGNORECASE)

        # Check what it is
        if line_matches_command("PROTOCOLINFO"):
            # Stem call PROTOCOLINFO before authenticating. Tell the
            # client that there is no authentication.
            respond("250-PROTOCOLINFO 1")
            respond("250-AUTH METHODS=NULL")
            respond("250-VERSION Tor=\"{}\"".format(controller.get_version()))
            respond("250 OK")

        elif line_matches_command("AUTHENTICATE"):
            # We have already authenticated, and the filtered port is
            # access-restricted to the allowed users via the firewall.
            respond("250 OK")

        # The client will be fooled that it is subscribing to all
        # events it requested, but we will only let through allowed
        # events.
        elif line_matches_command("SETEVENTS"):
            events = line.split(' ')[1:]
            if len(events) > 0:
                for event in events:
                    if event in allowed_events:
                        def event_cb(event):
                            respond(event.raw_content())
                        controller.add_event_listener(event_cb, getattr(EventType, event))
                        subscribed_event_listeners.append(event_cb)
                respond("250 OK")
            else:
                for listener in subscribed_event_listeners:
                    controller.remove_event_listener(listener)
                subscribed_event_listeners = []
                respond("250 OK")

        else:
            cmd_allowed = False
            cmd, _, args = line.partition(' ')
            cmd = cmd.upper()
            allowed_args = allowed_commands.get(cmd, [])
            if any([re.match(regex + "$", args) for regex in allowed_args]):
                response = controller.msg(line)
                respond(response.raw_content(), raw = True)
            else:
                print("Command filtered: " + line)
                respond("510 Command filtered")


class FilteredControlPortProxyHandler(socketserver.StreamRequestHandler):

    def setup(self):
        super(type(self), self).setup()
        self.filters = []
        for filter_file in glob.glob('/etc/tor-controlport-filter.d/*.yml'):
            with open(filter_file, "rb") as fh:
                self.filters += yaml.load(fh.read())

    def connect_to_real_control_port(self):
        # Read authentication cookie
        with open("/var/run/tor/control.authcookie", "rb") as f:
            cookie = f.read(32)

        # Connect to the real control port
        controller = Controller.from_socket_file("/var/run/tor/control")
        try:
            controller.authenticate(cookie)
        except SocketError:
            raise UnexpectedAnswer("AUTHENTICATE failed")

        return controller

    def handle(self):
        client_conn = next(conn for conn in psutil.net_connections() if conn.laddr == self.client_address)
        client_proc = psutil.Process(client_conn.pid)
        client_cmdline = " ".join(client_proc.cmdline())
        client_filter = next(filter for filter in self.filters if any([cmdline for cmdline in filter['cmdline'] if client_cmdline.startswith(cmdline)]))
        allowed_commands = client_filter.get('commands', {})
        allowed_events = client_filter.get('events', [])
        controller = self.connect_to_real_control_port()
        try:
            handle_controlport_session(controller, self.rfile, self.wfile, allowed_commands, allowed_events)
        finally:
            controller.close()


def main():
    listen_port = 9052
    server = socketserver.ThreadingTCPServer(("localhost", listen_port),
                                             FilteredControlPortProxyHandler)
    print("Tor control port filter started, listening on %d" % listen_port)
    try:
        server.serve_forever()
    finally:
        server.server_close()


if __name__ == "__main__":
    main()
