#!/bin/sh

set -e

# Do not use virtual machine proxy before apt-cacher-ng is installed
if [ "$http_proxy" = "http://$(hostname -f):3142" ] &&
   ! [ -f /etc/apt-cacher-ng/acng.conf ]; then
	LOCAL_HTTP_PROXY="$http_proxy"
	http_proxy=''
fi

# Uninstall custom Ikiwiki in case the build directory is still there
if [ -d /home/vagrant/ikiwiki ]; then
	rm -f /usr/local/bin/ikiwiki*
	rm -rf /usr/local/lib/perl/5.10.1/auto/IkiWiki
	rm -rf /usr/local/share/perl/5.10.1/
	rm -rf /home/vagrant/ikiwiki
fi

# Add unstable repository for ikiwiki, and pin it low
echo 'deb http://http.debian.net/debian unstable main' > /etc/apt/sources.list.d/unstable.list
sed -e 's/^[[:blank:]]*//' > /etc/apt/preferences.d/unstable <<EOF
	Package: *
	Pin: release a=unstable
	Pin-Priority: 99
EOF
sed -e 's/^[[:blank:]]*//' > /etc/apt/preferences.d/ikiwiki <<EOF
	Package: ikiwiki
	Pin: release a=unstable
	Pin-Priority: 500
EOF

apt-get update
apt-get -y install apt-cacher-ng

# Install custom configuration for apt-cacher-ng and restart
install -o root -g root -m 644 /vagrant/provision/assets/acng.conf /etc/apt-cacher-ng/acng.conf
service apt-cacher-ng restart

# Restore local HTTP proxy if needed
if [ "$LOCAL_HTTP_PROXY" ]; then
	http_proxy="$LOCAL_HTTP_PROXY"
fi

# Upgrade if needed
apt-get -y dist-upgrade

# Those are needed to build Tails
apt-get -y install \
	live-build \
	eatmydata/squeeze-backports \
	time whois \
	dpkg-dev \
	git \
	aufs-tools \
	ikiwiki \
	intltool

# Be sure to get all the modules we need for our Ikiwiki
apt-get -y --no-install-recommends install \
       libyaml-perl libyaml-libyaml-perl po4a perlmagick libyaml-syck-perl \
       libfile-chdir-perl liburi-perl libhtml-parser-perl wdg-html-validator \
       libhtml-scrubber-perl libhtml-template-perl libtimedate-perl \
       libxml-simple-perl libtext-multimarkdown-perl

# Add build script
install -o root -g root -m 755 /vagrant/provision/assets/build-tails /usr/local/bin

update_live_build_conf()
{
	local var="$1"
	local value="$2"

	mkdir -p /etc/live
	touch /etc/live/build.conf
	sed -e "/^[[:space:]]*$var=/d" -i /etc/live/build.conf
	echo "$var='$value'" >> /etc/live/build.conf
}

# Force APT repositories to a fixed mirror
update_live_build_conf LB_MIRROR_BINARY "http://ftp.us.debian.org/debian/"
update_live_build_conf LB_PARENT_MIRROR_BINARY "http://ftp.us.debian.org/debian/"
