#!/bin/sh

set -e

# Those are needed to build Tails
apt-get -y install \
	live-build \
	eatmydata/squeeze-backports \
	time whois \
	dpkg-dev \
	git

# Let's build a custom Ikiwiki
apt-get -y --no-install-recommends install \
	libyaml-perl libyaml-libyaml-perl po4a perlmagick libyaml-syck-perl \
	libfile-chdir-perl liburi-perl libhtml-parser-perl wdg-html-validator \
	libhtml-scrubber-perl libhtml-template-perl libtimedate-perl \
	libxml-simple-perl libtext-multimarkdown-perl

# Looks like gaffer is broken. *sigh*
#su - vagrant -c '
#set -e
#cd /home/vagrant
#test -d ikiwiki || git clone git://gaffer.ptitcanardnoir.org/ikiwiki.git
#cd ikiwiki
#git fetch origin
#git checkout mirrorlist || true
#git reset --hard origin/mirrorlist
#./Makefile.PL
#make
#'

su - vagrant -c '
set -e
cd /home/vagrant
test -d ikiwiki || git clone git://git.ikiwiki.info/ ikiwiki
cd ikiwiki
git fetch origin
git checkout master || true
git reset --hard origin/master
./Makefile.PL
make
'

(cd /home/vagrant/ikiwiki && make install)

# Add build script
cp /vagrant/provision/assets/build-tails /usr/local/bin
