#!/bin/sh

# This information is needed by the Unsafe Browser.

# Run only when the interface is not "lo":
if [ $1 = "lo" ]; then
   exit 0
fi

# Run whenever an interface gets "up", not otherwise:
if [ $2 != "up" ]; then
   exit 0
fi

echo "IP4_NAMESERVERS=\"${IP4_NAMESERVERS}\""  > /var/lib/NetworkManager/env
