# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Tails: The Amnesic Incognito Live System
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

$:.unshift File.expand_path('../lib', __FILE__)
require 'tails_build_settings'

Vagrant.configure("2") do |config|
  config.vm.box = 'tails-builder-20141201+libvirt'
  config.vm.box_url = 'http://dl.amnesia.boum.org/tails/project/vagrant/tails-builder-20141201+libvirt.box'
  config.vm.box_download_checksum_type = "sha256"
  config.vm.box_download_checksum =
    '6684003f619d8ba9c86028e12817c9ec0a0b23aa08d84fb395c403746f9c1671'
  config.vm.provision "shell", inline: <<-EOF
    sudo http_proxy='#{ENV['http_proxy']}' /vagrant/provision/setup-tails-builder
  EOF
  config.vm.synced_folder '.', '/vagrant', type: '9p', readonly: true
  config.vm.synced_folder '../.git', '/amnesia.git', type: '9p', readonly: true
  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = 'kvm'
    libvirt.connect_via_ssh = false
    libvirt.machine_arch = 'x86_64'
    libvirt.machine_type = 'q35'
    libvirt.emulator_path = '/usr/bin/qemu-system-x86_64'
    if ENV['TAILS_RAM_BUILD']
      libvirt.memory = VM_MEMORY_FOR_RAM_BUILDS
    else
      libvirt.memory = VM_MEMORY_FOR_DISK_BUILDS
    end
    cpus = ENV['TAILS_BUILD_CPUS']
    libvirt.cpus = cpus unless cpus.nil?
  end
end
