#!/bin/sh
#
# Copy this hook to .git/hooks/pre-commit
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

# set -x
#
if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Redirect output to stderr.
exec 1>&2

# If we try to commit po files, check that they do not contain errors.
if test $(git diff --ignore-submodules --name-only --exit-code -- . '*.po' $against |
    LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0 ; then
    if ! ./wiki/src/contribute/l10n_tricks/check_po.sh ; then
        echo
        echo "The po files you're trying to commit contain errors. Please fix them and try again."
        echo
        exit 1
    fi
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
