#! /bin/sh
### BEGIN INIT INFO
# Provides:          tails-disable-init-concurrency
# Required-Start:    gdm3
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      
# Short-Description: Disable init concurrency
# Description:       Disable init concurrency
### END INIT INFO

# Author: T(A)ILS developers <amnesia@boum.org>

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/usr/sbin:/usr/bin:/sbin:/bin
DESC="Disabling init concurrency"
NAME=tails-detect-virtualization
VIRTWHAT=/usr/sbin/virt-what
SCRIPTNAME=/etc/init.d/$NAME

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

do_start()
{
	echo 'CONCURRENCY=none' >> /etc/default/rcS
}

case "$1" in
  start)
	[ "$VERBOSE" != no ] && log_daemon_msg "$DESC" "$NAME"
	do_start
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  restart|reload|stop|force-reload)
	:
	;;
  *)
	echo "Usage: $SCRIPTNAME start" >&2
	exit 3
	;;
esac

:
