#! /bin/sh
### BEGIN INIT INFO
# Provides:          tails-wifi
# Required-Start:    mountkernfs $local_fs
# Required-Stop:     $local_fs
# Default-Start:     S
# Default-Stop:      
# Short-Description: Configure wireless interfaces
# Description:       T(A)ILS-specific wireless configuration
### END INIT INFO

# Author: amnesia <amnesia@boum.org>

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/bin
DESC="T(A)ILS-specific wireless configuration"
NAME=tails-wifi
IWCONFIG=/sbin/iwconfig
SCRIPTNAME=/etc/init.d/$NAME

# Exit if the package is not installed
[ -x "$IWCONFIG" ] || exit 0

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

do_start()
{
	wdevs=`iwconfig 2>/dev/null | grep -oE '^[^ ]+'`
	for dev in ${wdevs}; do
		iwconfig ${dev} power on
	done
}

case "$1" in
  start)
	[ "$VERBOSE" != no ] && log_daemon_msg "Setting up $DESC" "$NAME"
	do_start
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  restart|reload|stop|force-reload)
	:
	;;
  *)
	echo "Usage: $SCRIPTNAME start" >&2
	exit 3
	;;
esac

:
