#! /bin/sh
### BEGIN INIT INFO
# Provides:          tails-sdmem-on-media-removal
# Required-Start:    udev $local_fs memlockd tails-reconfigure-memlockd tails-reconfigure-kexec
# Required-Stop:     $local_fs memlockd
# Default-Start:     2 3 4 5
# Default-Stop:      0 6
# Short-Description: Wipe memory on live media removal.
# Description:       Tails-specific memory wiping script in case the live media is removed.
### END INIT INFO

# Author: Tails developers <amnesia@boum.org>

PATH=/usr/local/sbin/:/sbin:/bin
DESC="memory wiping on live media removal"
NAME=tails-sdmem-on-media-removal
WATCHDOG=/usr/local/sbin/udev-watchdog-wrapper
SCRIPTNAME=/etc/init.d/$NAME
PIDFILE=/var/run/udev-watchdog

# Exit if the package is not installed
[ -x "$WATCHDOG" ] || exit 0

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

case "$1" in
  start)
	log_daemon_msg "Setting up $DESC"
	$WATCHDOG &
	case "$?" in
		0|1)
			sleep 5 && /bin/pidof /usr/local/sbin/udev-watchdog > $PIDFILE
			log_end_msg 0
			;;
		2) log_end_msg 1 ;;
	esac
	;;
  stop)
	log_daemon_msg "Stopping $DESC"
	kill `cat $PIDFILE`
	case "$?" in
		0|1)
			rm -f $PIDFILE
			log_end_msg 0
			;;
		2) log_end_msg 1 ;;
	esac
	;;
  restart|reload|force-reload|status)
	# No-op
	;;
  *)
echo "Usage: $SCRIPTNAME start|stop" >&2
	exit 3
	;;
esac

:
