#! /bin/sh
### BEGIN INIT INFO
# Provides:		tails-reconfigure-memlockd
# Required-Start:	$local_fs memlockd
# Required-Stop:	
# Default-Start:        2 3 4 5
# Default-Stop:		
# Short-Description:    Reconfigure memlockd depending on running kernel
# Description:          Reconfigure memlockd depending on running kernel
### END INIT INFO

MEMLOCKD_CONF=/etc/memlockd.cfg

case "$1" in
  start)
	/usr/local/bin/tails-get-bootinfo kernel >> "$MEMLOCKD_CONF"
	/usr/local/bin/tails-get-bootinfo initrd >> "$MEMLOCKD_CONF"
	service memlockd restart
	;;
  *)
	echo "Usage: $0 start" >&2
	exit 3
	;;
esac
exit 0
