#! /bin/sh
### BEGIN INIT INFO
# Provides:		tails-reconfigure-memlockd
# Required-Start:	$local_fs memlockd
# Required-Stop:	
# Default-Start:        2 3 4 5
# Default-Stop:		
# Short-Description:    Reconfigure memlockd depending on running kernel
# Description:          Reconfigure memlockd depending on running kernel
### END INIT INFO

PATH="/usr/local/bin:${PATH}"
MEMLOCKD_CONF=/etc/memlockd.cfg

case "$1" in
  start)
	tails-boot-to-kexec kernel $(tails-get-bootinfo kernel) \
		>> "$MEMLOCKD_CONF"
	tails-boot-to-kexec initrd $(tails-get-bootinfo initrd) \
		>> "$MEMLOCKD_CONF"
	service memlockd restart
	;;
  *)
	echo "Usage: $0 start" >&2
	exit 3
	;;
esac
exit 0
