#! /bin/sh
### BEGIN INIT INFO
# Provides:		tails-reconfigure-kexec
# Required-Start:	$local_fs
# Required-Stop:	
# Default-Start:        2 3 4 5
# Default-Stop:		
# Short-Description:    Reconfigure kexec depending on running kernel
# Description:          Reconfigure kexec depending on running kernel
### END INIT INFO

KEXEC_CONF=/etc/default/kexec

case "$1" in
  start)
	echo "KERNEL_IMAGE=\"$(/usr/local/bin/tails-get-bootinfo kernel)\"" >> "$KEXEC_CONF"
	echo "INITRD=\"$(/usr/local/bin/tails-get-bootinfo initrd)\"" >> "$KEXEC_CONF"
	if grep -qw debug=wipemem /proc/cmdline; then
	   echo 'APPEND="${APPEND} wipememdebug=1"' >> "$KEXEC_CONF"
	fi
	;;
  *)
	echo "Usage: $0 start" >&2
	exit 3
	;;
esac
exit 0
