#! /bin/sh
### BEGIN INIT INFO
# Provides:          tails-kexec-cache
# Required-Start:
# Required-Stop:
# Should-Stop:       live-boot tails-kexec
# Default-Start:
# Default-Stop:      0 6
# X-Stop-After:      kexec-load umountroot
# Short-Description: Cache files needed by kexec
# Description:       Cache files needed by /etc/init.d/tails-kexec
### END INIT INFO

# Author: T(A)ILS developers <amnesia@boum.org>

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/usr/sbin:/usr/bin:/sbin:/bin
DESC="Caching files needed by kexec"
NAME=tails-kexec-cache
SCRIPTNAME=/etc/init.d/$NAME

. /lib/lsb/init-functions

cache_path()
{
	path="${1}"

	if [ -d "${path}" ]
	then
		find "${path}" -type f | xargs cat > /dev/null 2>&1
	elif [ -f "${path}" ]
	then
		if [ -x "${path}" ]
		then
			if file -L "${path}" | grep -q 'dynamically linked'
			then
				for lib in $(ldd "${path}" | awk '{ print $3 }')
				do
					cache_path "${lib}"
				done
			fi
		fi

		cat "${path}" >/dev/null 2>&1
	fi
}

do_stop() {
   log_action_begin_msg "$DESC"
   for path in /bin/sh /etc/init.d/tails-kexec /bin/stty /bin/cat /bin/sleep /sbin/kexec /etc/default/locale ; do
      cache_path "$path"
   done
   log_action_end_msg 0
}

case "$1" in
   start)
      # No-op
      ;;
   restart|reload|force-reload)
      echo "Error: argument '$1' not supported" >&2
      exit 3
      ;;
   stop)
      do_stop
      ;;
   *)
      echo "Usage: $0 start|stop" >&2
      exit 3
      ;;
esac

exit 0
