#! /bin/sh
### BEGIN INIT INFO
# Provides:		tails-set-wireless-devices-state
# Required-Start:	mountkernfs $local_fs udev
# Required-Stop:	
# Default-Start:        2 3 4 5
# Default-Stop:		
# Short-Description:    Set proper default state on wireless devices
# Description:          Set proper default state on wireless devices
### END INIT INFO

case "$1" in
   start)
      /usr/local/sbin/tails-set-wireless-devices-state &
      ;;
   *)
      echo "Usage: $0 start" >&2
      exit 3
      ;;
esac
exit 0
