#! /bin/sh
### BEGIN INIT INFO
# Provides:             tor-controlport-filter
# Required-Start:       $remote_fs
# Required-Stop:
# Default-Start:        2 3 4 5
# Default-Stop:
# Short-Description:    Tor control port filter proxy
# Description:          Tor control port filter proxy
### END INIT INFO

case "$1" in
	start)
		start-stop-daemon \
			--start \
			--quiet \
			--background \
			--chuid tor-controlport-filter:tor-controlport-filter \
			--exec /usr/local/sbin/tor-controlport-filter
		;;
	*)
		echo "Usage: $0 start" >&2
		exit 3
		;;
esac

exit 0
