#!/bin/sh

LIVE_USER_UID=999
LIVE_USER_GID=999

Bootstrap_permissions ()
{
	echo "- bootstrapping permissions"
	chown -R "${LIVE_USER_UID}":"${LIVE_USER_GID}" "/home/${LIVE_USERNAME}"

	# Creating state file
	touch /var/lib/live/config/permissions-bootstrap
}

Bootstrap_permissions
