#!/bin/sh

Configure_resolv_conf ()
{

	echo -n " resolv-conf"
	rm -f /etc/resolv.conf
	ln -s /etc/resolvconf/run/resolv.conf /etc/resolv.conf

	# Creating state file
	touch /var/lib/live/config/resolv-conf
}

Configure_resolv_conf
