#!/bin/sh

Import_GnuPG_key ()
{
	echo -n "import-gnupg-key"
	sudo -H -u "${LIVE_USERNAME}" gpg --batch --import /usr/share/doc/amnesia/amnesia.asc

	# Creating state file
	touch /var/lib/live/config/import-gnupg-key	
}

Import_GnuPG_key
