#!/bin/sh

Import_GnuPG_key ()
{
	echo "- importing Tails' GnuPG keys into the ${LIVE_USERNAME}'s keyring"
	sudo -H -u "${LIVE_USERNAME}" gpg --batch --import /usr/share/doc/tails/website/*.key

	echo "- importing Tails' GnuPG signing key into tails-iuk's trusted keyring"
	gpg --batch --homedir /usr/share/tails-iuk/trusted_gnupg_homedir \
	    --import /usr/share/doc/tails/website/tails-signing.key
	chmod -R go+rX /usr/share/tails-iuk

	echo "- importing Tails help desk's GnuPG key into WhisperBack's keyring"
	gpg --batch --no-default-keyring \
	    --keyring /usr/share/keyrings/whisperback-keyring.gpg \
	    --import /usr/share/doc/tails/website/tails-bugs.key
	chmod a+r /usr/share/keyrings/whisperback-keyring.gpg

	# Creating state file
	touch /var/lib/live/config/import-gnupg-key	
}

Import_GnuPG_key
