#!/bin/sh

Localize ()
{
   echo "- localizing the user environment"
   # $LANG was set there by the FIXME live-config upstream script
   . /etc/default/locale

   LANGUAGE="`echo ${LANG} | head -c 2`"

   ### Nautilus wipe script

   if [ ! -d "/home/${LIVE_USERNAME}/.gnome2/nautilus-scripts/" ] ; then
      mkdir -p "/home/${LIVE_USERNAME}/.gnome2/nautilus-scripts/"
   fi

   case "${LANGUAGE}" in
      es)
	 NAME="Eliminar_de_forma_segura"
	 ;;
      fr)
	 NAME="Supprimer_en_ecrasant_les_donnees"
	 ;;
      *)
	 NAME="Securely_erase"
	 ;;
   esac

   ln -s "/usr/local/bin/nautilus-wipe" "/home/${LIVE_USERNAME}/.gnome2/nautilus-scripts/${NAME}"

   ### Scroogle

   if [ -r "/usr/share/amnesia/iceweasel/searchplugins/scroogle-ssl-${LANGUAGE}.xml" ]; then
      cp "/usr/share/amnesia/iceweasel/searchplugins/scroogle-ssl-${LANGUAGE}.xml" \
	 /usr/share/iceweasel/searchplugins/
   fi

	# Creating state file
	touch /var/lib/live/config/localize
}

Localize
