#!/bin/sh

Localize ()
{
   echo "- localizing the user environment"
   # $LANG was set there by the FIXME live-config upstream script
   . /etc/default/locale

   LANGUAGE="`echo ${LANG} | head -c 2`"

   ### Scroogle

   if [ -r "/usr/share/amnesia/iceweasel/searchplugins/scroogle-ssl-${LANGUAGE}.xml" ]; then
      cp "/usr/share/amnesia/iceweasel/searchplugins/scroogle-ssl-${LANGUAGE}.xml" \
	 /usr/share/iceweasel/distribution/searchplugins/common/
   fi

   ### Startpage

   if [ -r "/usr/share/amnesia/iceweasel/searchplugins/startpage-https-${LANGUAGE}.xml" ]; then
      cp "/usr/share/amnesia/iceweasel/searchplugins/startpage-https-${LANGUAGE}.xml" \
	 /usr/share/iceweasel/distribution/searchplugins/common/
   fi

	# Creating state file
	touch /var/lib/live/config/localize
}

Localize
