#!/bin/sh

Install_TrueCrypt ()
{
	# Only install TrueCrypt when "truecrypt" appers on kernel command line
	grep -qw "truecrypt" /proc/cmdline || return 0

	echo "- Installing TrueCrypt"

	# Create temporary directory to extract upstream tarball
	TMPDIR=$(mktemp -d) || return 1
	trap "rm -rf '$TMPDIR'" EXIT

	# Find upstream tarball
	UPSTREAM_TARBALL="$(find /usr/share/amnesia -type f \
		-name 'truecrypt-*-linux-x86.tar.gz' | sort -n | tail -n 1)"

	# Unpack upstream tarball and lookup setup binary
	INSTALLER="$(tar -C "$TMPDIR" -zvxf "$UPSTREAM_TARBALL" | grep -- '-setup-x86$')"

	expect >/var/log/truecrypt-installer.log <<-EOF
		set timeout 30

		spawn "$TMPDIR/$INSTALLER"
		expect "To select, enter 1 or 2:"
		send "1\n"
		expect "Press Enter to display the license terms..."
		send "\n"
		expect "\n:"
		send "q"
		expect "Do you accept and agree to be bound by the license terms? (yes/no):"
		send "yes\n"
		expect "Press Enter to exit..."
		send "\n"
	EOF
}

Install_TrueCrypt
