#!/bin/sh
#
# Recreate files (eg. /var/lib/systemd/catalog/database, /etc/machine-id, etc.)
# at boot-time as we remove them to ensure a deterministic build.

echo "- configuring systemd"

systemd-machine-id-setup

journalctl --update-catalog
