#!/bin/sh

# This script sets up the amnesia user's Gnome theme to something that
# resembles Microsoft Windows XP.
#
# The script is based on the XpGnome installation script, written by
# PhrankDaChicken, available from http://ubunut.online02.com/xpgnome

# only run if "winxp" is on the kernel command line
grep -qw winxp /proc/cmdline || return 0

gconf_set() {
	sudo -H -u "${LIVE_USERNAME}" gconftool-2 --set "$@"
}

# Icon theme
gconf_set "/desktop/gnome/interface/icon_theme" --type string "GnomeXP"

# Cursor theme
gconf_set "/desktop/gnome/peripherals/mouse/cursor_theme" --type string "xp-cursor"

# GTK theme
gconf_set "/desktop/gnome/interface/gtk_theme" --type string "XPLuna"

# Metacity theme
gconf_set "/apps/metacity/general/theme" --type string "XPLuna"

# Toolbars - Icons Only
gconf_set "/desktop/gnome/interface/toolbar_style" --type string "icons"
# Nautilus Sidebar
gconf_set "/apps/nautilus/preferences/side_pane_view" --type string "NautilusTreeSidebar"
gconf_set "/apps/nautilus/sidebar_panels/tree/show_only_directories" --type bool TRUE

# FIXME: Localization needed below
# Desktop Icons
gconf_set "/apps/nautilus/desktop/computer_icon_visible" --type bool TRUE
gconf_set "/apps/nautilus/desktop/computer_icon_name" --type string "My Computer"
gconf_set "/apps/nautilus/desktop/home_icon_visible" --type bool TRUE
gconf_set "/apps/nautilus/desktop/home_icon_name" --type string "My Documents"
gconf_set "/apps/nautilus/desktop/network_icon_visible" --type bool TRUE
gconf_set "/apps/nautilus/desktop/network_icon_name" --type string "My Network Places"
gconf_set "/apps/nautilus/desktop/trash_icon_visible" --type bool TRUE
gconf_set "/apps/nautilus/desktop/trash_icon_name" --type string "Recycle Bin"
gconf_set "/apps/nautilus/desktop/volumes_visible" --type bool FALSE

# Background
gconf_set "/desktop/gnome/background/picture_filename" --type string "/usr/share/pixmaps/backgrounds/xp-bliss.jpg"
gconf_set "/desktop/gnome/background/picture_options" --type string "stretched"

# Set One Workplace
gconf_set "/apps/metacity/general/num_workspaces" --type int 1

## Panel Stuff
# Create New Panel
gconf_set "/apps/panel/toplevels/bottom_panel_0/animation_speed" --type string "medium"
gconf_set "/apps/panel/toplevels/bottom_panel_0/auto_hide" --type bool FALSE
gconf_set "/apps/panel/toplevels/bottom_panel_0/auto_hide_size" --type int 6
gconf_set "/apps/panel/toplevels/bottom_panel_0/enable_animations" --type bool TRUE
gconf_set "/apps/panel/toplevels/bottom_panel_0/enable_arrows" --type bool TRUE
gconf_set "/apps/panel/toplevels/bottom_panel_0/enable_buttons" --type bool FALSE
gconf_set "/apps/panel/toplevels/bottom_panel_0/expand" --type bool TRUE
gconf_set "/apps/panel/toplevels/bottom_panel_0/hide_delay" --type int 500
gconf_set "/apps/panel/toplevels/bottom_panel_0/monitor" --type int 0
gconf_set "/apps/panel/toplevels/bottom_panel_0/name" --type string "bottom_panel_0"
gconf_set "/apps/panel/toplevels/bottom_panel_0/orientation" --type string "bottom"
gconf_set "/apps/panel/toplevels/bottom_panel_0/screen" --type int 0
gconf_set "/apps/panel/toplevels/bottom_panel_0/size" --type int 32
gconf_set "/apps/panel/toplevels/bottom_panel_0/unhide_delay" --type int 500 
gconf_set "/apps/panel/toplevels/bottom_panel_0/x" --type int 0
gconf_set "/apps/panel/toplevels/bottom_panel_0/x_centered" --type bool FALSE
gconf_set "/apps/panel/toplevels/bottom_panel_0/x_right" --type int 0
gconf_set "/apps/panel/toplevels/bottom_panel_0/y" --type int 0
gconf_set "/apps/panel/toplevels/bottom_panel_0/y_bottom" --type  int 0 
gconf_set "/apps/panel/toplevels/bottom_panel_0/y_centered" --type bool FALSE

gconf_set "/apps/panel/toplevels/bottom_panel_0/background/color" --type string "#ffffff"
gconf_set "/apps/panel/toplevels/bottom_panel_0/background/fit" --type bool FALSE
gconf_set "/apps/panel/toplevels/bottom_panel_0/background/image" --type string ""
gconf_set "/apps/panel/toplevels/bottom_panel_0/background/opacity" --type int 6000
gconf_set "/apps/panel/toplevels/bottom_panel_0/background/rotate" --type bool FALSE
gconf_set "/apps/panel/toplevels/bottom_panel_0/background/stretch" --type bool FALSE
gconf_set "/apps/panel/toplevels/bottom_panel_0/background/type" --type string "gtk"

# Start Menu
gconf_set "/apps/panel/objects/object_0/action_type" --type string "lock"
gconf_set "/apps/panel/objects/object_0/attached_toplevel_id" --type string ""
gconf_set "/apps/panel/objects/object_0/bonobo_iid" --type string ""
gconf_set "/apps/panel/objects/object_0/custom_icon" --type string "/usr/share/themes/XPLuna/start.png"
gconf_set "/apps/panel/objects/object_0/launcher_location" --type string ""
gconf_set "/apps/panel/objects/object_0/locked" --type bool TRUE
gconf_set "/apps/panel/objects/object_0/menu_path" --type string "applications:/"
gconf_set "/apps/panel/objects/object_0/object_type" --type string "menu-object"
gconf_set "/apps/panel/objects/object_0/panel_right_stick" --type bool FALSE
gconf_set "/apps/panel/objects/object_0/position" --type int 0
gconf_set "/apps/panel/objects/object_0/tooltip" --type string "Main Menu"
gconf_set "/apps/panel/objects/object_0/toplevel_id" --type string "bottom_panel_0"
gconf_set "/apps/panel/objects/object_0/use_custom_icon" --type bool TRUE
gconf_set "/apps/panel/objects/object_0/use_menu_path" --type bool FALSE

# Show Desktop
gconf_set "/apps/panel/applets/applet_0/action_type" --type string "lock"
gconf_set "/apps/panel/applets/applet_0/attached_toplevel_id" --type string ""
gconf_set "/apps/panel/applets/applet_0/bonobo_iid" --type string "OAFIID:GNOME_ShowDesktopApplet"
gconf_set "/apps/panel/applets/applet_0/custom_icon" --type string ""
gconf_set "/apps/panel/applets/applet_0/launcher_location" --type string ""
gconf_set "/apps/panel/applets/applet_0/locked" --type bool TRUE
gconf_set "/apps/panel/applets/applet_0/menu_path" --type string "applications:/"
gconf_set "/apps/panel/applets/applet_0/object_type" --type string "bonobo-applet"
gconf_set "/apps/panel/applets/applet_0/panel_right_stick" --type bool FALSE
gconf_set "/apps/panel/applets/applet_0/position" --type int 1
gconf_set "/apps/panel/applets/applet_0/tooltip" --type string ""
gconf_set "/apps/panel/applets/applet_0/toplevel_id" --type string "bottom_panel_0"
gconf_set "/apps/panel/applets/applet_0/use_custom_icon" --type bool FALSE
gconf_set "/apps/panel/applets/applet_0/use_menu_path" --type bool FALSE

# Window Switcher
gconf_set "/apps/panel/applets/applet_1/action_type" --type string "lock"
gconf_set "/apps/panel/applets/applet_1/attached_toplevel_id" --type string ""
gconf_set "/apps/panel/applets/applet_1/bonobo_iid" --type string "OAFIID:GNOME_WindowListApplet"
gconf_set "/apps/panel/applets/applet_1/custom_icon" --type string ""
gconf_set "/apps/panel/applets/applet_1/launcher_location" --type string ""
gconf_set "/apps/panel/applets/applet_1/locked" --type bool TRUE
gconf_set "/apps/panel/applets/applet_1/menu_path" --type string "applications:/"
gconf_set "/apps/panel/applets/applet_1/object_type" --type string "bonobo-applet"
gconf_set "/apps/panel/applets/applet_1/panel_right_stick" --type bool FALSE
gconf_set "/apps/panel/applets/applet_1/position" --type int 2
gconf_set "/apps/panel/applets/applet_1/tooltip" --type string ""
gconf_set "/apps/panel/applets/applet_1/toplevel_id" --type string "bottom_panel_0"
gconf_set "/apps/panel/applets/applet_1/use_custom_icon" --type bool FALSE
gconf_set "/apps/panel/applets/applet_1/use_menu_path" --type bool FALSE

gconf_set "/apps/panel/applets/applet_1/prefs/display_all_workspaces" --type bool FALSE
gconf_set "/apps/panel/applets/applet_1/prefs/group_windows" --type string "never"
gconf_set "/apps/panel/applets/applet_1/prefs/maximum_size" --type int 4096
gconf_set "/apps/panel/applets/applet_1/prefs/minimum_size" --type int 50
gconf_set "/apps/panel/applets/applet_1/prefs/move_unminimized_windows" --type bool TRUE

# Notification Area
gconf_set "/apps/panel/applets/applet_2/action_type" --type string "lock"
gconf_set "/apps/panel/applets/applet_2/attached_toplevel_id" --type string ""
gconf_set "/apps/panel/applets/applet_2/bonobo_iid" --type string "OAFIID:GNOME_NotificationAreaApplet"
gconf_set "/apps/panel/applets/applet_2/custom_icon" --type string ""
gconf_set "/apps/panel/applets/applet_2/launcher_location" --type string ""
gconf_set "/apps/panel/applets/applet_2/locked" --type bool TRUE
gconf_set "/apps/panel/applets/applet_2/menu_path" --type string "applications:/"
gconf_set "/apps/panel/applets/applet_2/object_type" --type string "bonobo-applet"
gconf_set "/apps/panel/applets/applet_2/panel_right_stick" --type bool TRUE
gconf_set "/apps/panel/applets/applet_2/position" --type int 3
gconf_set "/apps/panel/applets/applet_2/tooltip" --type string ""
gconf_set "/apps/panel/applets/applet_2/toplevel_id" --type string "bottom_panel_0"
gconf_set "/apps/panel/applets/applet_2/use_custom_icon" --type bool FALSE
gconf_set "/apps/panel/applets/applet_2/use_menu_path" --type bool FALSE

# Volume Control
gconf_set "/apps/panel/applets/applet_3/action_type" --type string "lock"
gconf_set "/apps/panel/applets/applet_3/attached_toplevel_id" --type string ""
gconf_set "/apps/panel/applets/applet_3/bonobo_iid" --type string "OAFIID:GNOME_MixerApplet"
gconf_set "/apps/panel/applets/applet_3/custom_icon" --type string ""
gconf_set "/apps/panel/applets/applet_3/launcher_location" --type string ""
gconf_set "/apps/panel/applets/applet_3/locked" --type bool TRUE
gconf_set "/apps/panel/applets/applet_3/menu_path" --type string "applications:/"
gconf_set "/apps/panel/applets/applet_3/object_type" --type string "bonobo-applet"
gconf_set "/apps/panel/applets/applet_3/panel_right_stick" --type bool TRUE
gconf_set "/apps/panel/applets/applet_3/position" --type int 2
gconf_set "/apps/panel/applets/applet_3/tooltip" --type string ""
gconf_set "/apps/panel/applets/applet_3/toplevel_id" --type string "bottom_panel_0"
gconf_set "/apps/panel/applets/applet_3/use_custom_icon" --type bool FALSE
gconf_set "/apps/panel/applets/applet_3/use_menu_path" --type bool FALSE

# Clock
gconf_set "/apps/panel/applets/applet_4/action_type" --type string "lock"
gconf_set "/apps/panel/applets/applet_4/attached_toplevel_id" --type string ""
gconf_set "/apps/panel/applets/applet_4/bonobo_iid" --type string "OAFIID:GNOME_ClockApplet"
gconf_set "/apps/panel/applets/applet_4/custom_icon" --type string ""
gconf_set "/apps/panel/applets/applet_4/launcher_location" --type string ""
gconf_set "/apps/panel/applets/applet_4/locked" --type bool TRUE
gconf_set "/apps/panel/applets/applet_4/menu_path" --type string "applications:/"
gconf_set "/apps/panel/applets/applet_4/object_type" --type string "bonobo-applet"
gconf_set "/apps/panel/applets/applet_4/panel_right_stick" --type bool TRUE
gconf_set "/apps/panel/applets/applet_4/position" --type int 0
gconf_set "/apps/panel/applets/applet_4/tooltip" --type string ""
gconf_set "/apps/panel/applets/applet_4/toplevel_id" --type string "bottom_panel_0"
gconf_set "/apps/panel/applets/applet_4/use_custom_icon" --type bool FALSE
gconf_set "/apps/panel/applets/applet_4/use_menu_path" --type bool FALSE

gconf_set "/apps/panel/applets/applet_4/prefs/config_tool" --type string ""
gconf_set "/apps/panel/applets/applet_4/prefs/custom_format" --type string ""
gconf_set "/apps/panel/applets/applet_4/prefs/expand_appointments" --type bool TRUE
gconf_set "/apps/panel/applets/applet_4/prefs/expand_birthdays" --type bool TRUE
gconf_set "/apps/panel/applets/applet_4/prefs/expand_tasks" --type bool FALSE
gconf_set "/apps/panel/applets/applet_4/prefs/expand_weather" --type bool FALSE
gconf_set "/apps/panel/applets/applet_4/prefs/format" --type string "12-hour"
gconf_set "/apps/panel/applets/applet_4/prefs/gmt_time" --type bool FALSE
gconf_set "/apps/panel/applets/applet_4/prefs/hour_format" --type string "12"
gconf_set "/apps/panel/applets/applet_4/prefs/internet_time" --type bool FALSE
gconf_set "/apps/panel/applets/applet_4/prefs/show_date" --type bool FALSE
gconf_set "/apps/panel/applets/applet_4/prefs/show_seconds" --type bool FALSE
gconf_set "/apps/panel/applets/applet_4/prefs/show_timezones" --type bool FALSE
gconf_set "/apps/panel/applets/applet_4/prefs/show_tooltip" --type bool TRUE
gconf_set "/apps/panel/applets/applet_4/prefs/show_week_numbers" --type bool TRUE
gconf_set "/apps/panel/applets/applet_4/prefs/unix_time" --type bool FALSE
gconf_set "/apps/panel/applets/applet_4/prefs/timezones/tz_id_list" --type list --list-type string "[]"

# Add Panels Items
gconf_set "/apps/panel/general/applet_id_list" --type list --list-type string "[applet_0,applet_1,applet_2,applet_3,applet_4]"
gconf_set "/apps/panel/general/object_id_list" --type list --list-type string "[object_0]"
gconf_set "/apps/panel/general/toplevel_id_list" --type list --list-type string "[bottom_panel_0]"
