#!/bin/sh

SCRIPT=/usr/local/sbin/autotest_remote_shell.py

if grep -qw "autotest_never_use_this_option" /proc/cmdline; then
    # FIXME: more beautiful solution
    sed -i 's/^exit.*$//' /etc/rc.local
    echo "python ${SCRIPT} /dev/ttyS0 &" >> /etc/rc.local
    echo "exit 0" >> /etc/rc.local
fi
