#!/bin/sh

Fix_permissions ()
{
	echo "- fixing permissions"
	chown -R "${LIVE_USERNAME}":"${LIVE_USERNAME}" "/home/${LIVE_USERNAME}"
	chmod go= "/home/${LIVE_USERNAME}"

	# Creating state file
	touch /var/lib/live/config/permissions
}

Fix_permissions
