#!/bin/sh

SCRIPT=/usr/local/lib/tails-autotest-remote-shell

if grep -qw "autotest_never_use_this_option" /proc/cmdline; then
    # FIXME: more beautiful solution
    sed -i 's/^exit.*$//' /etc/rc.local
    echo "( while true ; do ${SCRIPT} /dev/ttyS0 ; done ) &" >> \
        /etc/rc.local
    echo "exit 0" >> /etc/rc.local
fi
