#!/bin/sh

# Make the default user password-less. This integrates well with pam
# e.g. for preventing screen locking to completely lock out users who
# don't set a password in Tails Greeter and don't know the default
# password (which previously was the default for Debian Live, namely
# "live").
passwd -d "${LIVE_USERNAME}"
