#!/bin/sh

PREREQ=""

prereqs() {
	echo "${PREREQ}"
}

case "${1}" in
    prereqs)
	prereqs
	exit 0
	;;
esac

# Do not readahead when "profile" appears on kernel command line
grep -qw "profile" /proc/cmdline && exit 0

READAHEAD_LIST="/root/usr/share/amnesia/readahead-list"
BACKGROUND_AT="^sbin/splashy$"

test -e "$READAHEAD_LIST" || exit 0

. /scripts/live-functions

log_begin_msg "Starting reading ahead boot files"

(cd /root
 xargs stat <"$READAHEAD_LIST" >/dev/null)
(cd /root
 sed -n "\:$BACKGROUND_AT:q;p" "$READAHEAD_LIST" | xargs cat >/dev/null)
(cd /root
 sed -n "\:$BACKGROUND_AT:,\$p" "$READAHEAD_LIST" | xargs cat >/dev/null) &

log_end_msg
