#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# live-initramfs header

. /scripts/live-functions

log_begin_msg "Configuring /etc/resolv.conf"

# live-initramfs script

chroot /root rm -f /etc/resolv.conf
chroot /root ln -s /etc/resolvconf/run/resolv.conf /etc/resolv.conf

log_end_msg
