#!/bin/sh

PREREQ=""

prereqs() {
	echo "${PREREQ}"
}

case "${1}" in
    prereqs)
	prereqs
	exit 0
	;;
esac

# Do not readahead when "profile" appears on kernel command line
grep -qw "profile" /proc/cmdline && exit 0

READAHEAD_LIST="/root/usr/share/amnesia/readahead-list"
BACKGROUND_AT="^etc/default/rsyslog$"

test -e "$READAHEAD_LIST" || exit 0

. /scripts/live-functions

log_begin_msg "Starting reading ahead boot files"

FG_FILES="$(sed -n "\:$BACKGROUND_AT:q;p" "$READAHEAD_LIST")"
BG_FILES="$(sed -n "\:$BACKGROUND_AT:,\$p" "$READAHEAD_LIST")"
FG_SIZE=$(
 cd /root
 echo "$FG_FILES" |
 xargs du -c 2>/dev/null |
 awk '$2 ~ /^total$/ { t = t + $1 } END { print t }')
(cd /root
 echo "$BG_FILES" |
 xargs stat >/dev/null 2>/dev/null)
(cd /root
 echo "$FG_FILES" |
 xargs cat 2>/dev/null |
 pv -f -s ${FG_SIZE}k >/dev/null)
(cd /root
 echo "$BG_FILES" | xargs cat >/dev/null 2>&1) &

log_end_msg
