#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# live-initramfs header

if [ -n "${NOUSER}" ]
then
	exit 0
fi

. /scripts/live-functions

log_begin_msg "Setting up GConf settings"

# live-initramfs script

gct() {
	chroot /root sudo -u "${USERNAME}" gconftool-2 "${@}"
}

for file in /usr/share/amnesia/gconf/*.xml ; do
   gct --load "${file}"
done

log_end_msg
