#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# live-initramfs header

if [ -n "${NOUSER}" ]; then
	exit 0
fi

. /scripts/live-functions

log_begin_msg "Editing onBoard settings"

# live-initramfs script

gct() {
	chroot /root sudo -u "${USERNAME}" gconftool-2 "${@}"
}

gct -t bool -s /apps/onboard/use_status_icon true
gct -t bool -s /apps/onboard/start_minimized true
gct -t list --list-type=string -s /apps/onboard/snippets '[https://amnesia.boum.org/]'

log_end_msg
