#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# live-initramfs header

if [ -n "${NOUSER}" ]
then
	exit 0
fi

. /scripts/live-functions

log_begin_msg "Editing Gnome proxy settings to use Tor"

# live-initramfs script

gct() {
	chroot /root sudo -u "${USERNAME}" gconftool-2 "${@}"
}

gct -t bool           -s /system/http_proxy/use_same_proxy      false
gct -t string         -s /system/http_proxy/host                localhost
gct -t int            -s /system/http_proxy/port                8118
gct -t bool           -s /system/http_proxy/use_authentication  false
gct -t string         -s /system/proxy/mode                     manual
gct -t string         -s /system/proxy/secure_host              localhost
gct -t int            -s /system/proxy/secure_port              8118
gct -t string         -s /system/proxy/ftp_host                 localhost
gct -t int            -s /system/proxy/ftp_port                 9050
gct -t string         -s /system/proxy/socks_host               localhost
gct -t int            -s /system/proxy/socks_port               9050
gct -t list --list-type=string -s /system/http_proxy/ignore_hosts '[localhost,127.0.0.0/8,192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,*.local]'

log_end_msg
