#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# live-initramfs header

if [ -n "${NOUSER}" ]
then
	exit 0
fi

. /scripts/live-functions

log_begin_msg "Importing amnesia's GnuPG key into the live session user's keyring"

# live-initramfs script

chroot /root sudo -u "${USERNAME}" gpg --batch --import /usr/share/doc/amnesia/amnesia.asc

log_end_msg
