#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# live-initramfs header

if [ -n "${NOUSER}" ]
then
	exit 0
fi

. /scripts/live-functions

log_begin_msg "Adding a localized secure-delete action to Nautilus"

# live-initramfs script

case "${LANGUAGE}" in
   fr)
      NAME="Effacer_definitivement"
      ;;
   *)
      NAME="Securely_erase"
      ;;
esac

if [ -x "/root/usr/local/bin/nautilus-wipe.${LANGUAGE}" ]; then
   DEST="/usr/local/bin/nautilus-wipe.${LANGUAGE}"
else
   DEST="/usr/local/bin/nautilus-wipe"
fi

chroot /root sudo -H -u "${USERNAME}" ln -s "${DEST}" "${HOME}/.gnome2/nautilus-scripts/${NAME}"

log_end_msg
