#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# live-initramfs header

if [ -n "${NOUSER}" ]
then
	exit 0
fi

. /scripts/live-functions

log_begin_msg "Randomizing Pidgin XMPP Resource field and nickname"

# live-initramfs script

# We use head to remove the trailing '==' + newline.
RESOURCE="`chroot /root openssl rand -base64 16 | head -c 22`"
NICKNAME_SUFFIX="`echo ${RESOURCE} | head -c 8`"

for file in accounts.xml blist.xml ; do
   chroot /root sudo -H -u "${USERNAME}" sed -i'' "s,XXX_RESOURCE_XXX,${RESOURCE}," "/home/${USERNAME}/.purple/${file}"
   chroot /root sudo -H -u "${USERNAME}" sed -i'' "s,XXX_NICKNAME_SUFFIX_XXX,${NICKNAME_SUFFIX}," "/home/${USERNAME}/.purple/${file}"
done

log_end_msg
