#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# live-initramfs header

if [ -n "${NOUSER}" ]
then
	exit 0
fi

. /scripts/live-functions

log_begin_msg "Randomizing Pidgin XMPP Resource field"

# live-initramfs script

RESOURCE="`chroot /root openssl rand -base64 16`"

for file in accounts.xml blist.xml ; do
   chroot /root sudo -H -u "${USERNAME}" sed -i'' "s,XXX_RESOURCE_XXX,${RESOURCE}," "/home/${USERNAME}/.purple/${file}"
done

log_end_msg
