#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# live-initramfs header

if [ -n "${NOUSER}" ]
then
	exit 0
fi

. /scripts/live-functions

log_begin_msg "Setting up GNOME panel"

# live-initramfs script

gct() {
	chroot /root sudo -u "${USERNAME}" gconftool-2 "${@}"
}

gct --load /usr/share/amnesia/gconf/gnome_panel.xml

log_end_msg
