#!/bin/sh

#set -e

# initramfs-tools header

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

# live-initramfs header

if [ -n "${NOUSER}" ]
then
	exit 0
fi

. /scripts/live-functions

log_begin_msg "Fixing permissions on /home/${USERNAME}"

# live-initramfs script

chown -R "${USERNAME}":"${USERNAME}" "/root/home/${USERNAME}"

log_end_msg
