#!/bin/sh

set -e
set -u

echo "Installing the tailslib python library"

# Import ensure_hook_dependency_is_installed() and strip_nondeterminism_wrapper()
. /usr/local/lib/tails-shell-library/build.sh

ensure_hook_dependency_is_installed python3-setuptools

(
    cd /tmp/pythonlib
    python3 setup.py clean
    python3 setup.py install

    # Strip nondeterministic information from tailslib
    package_glob_pattern="/usr/local/lib/python3.*/dist-packages/Tailslib*.egg"
    for egg in ${package_glob_pattern}; do
        if [ ! -f "${egg}" ]; then
            echo "Cannot find Tailslib Python package \"${package_glob_pattern}\"" >&2
            exit 1
        fi
        strip_nondeterminism_wrapper --type zip ${egg} 2>/dev/null
    done
)
rm -rf /tmp/pythonlib
