#!/bin/sh

set -e
set -u

echo "Installing the tailslib python library"

# Import ensure_hook_dependency_is_installed()
. /usr/local/lib/tails-shell-library/build.sh

ensure_hook_dependency_is_installed python3-setuptools

(
    cd /tmp/pythonlib
    python3 setup.py clean
    python3 setup.py install
)
rm -rf /tmp/pythonlib
