#! /bin/sh

set -e

echo "Configuring APT architectures for the duration of chroot_local-hooks"

echo 'APT::Architectures {"i386"; "amd64";};' \
     > /etc/apt/apt.conf.d/13architectures

apt-get update
