#!/bin/sh

set -e

# Create the tails-persistence-setup user.
#
# The tails-persistence-setup program may be run as this user.
# This allows us to give it special privileges (e.g. access via udisk
# to internal disks and to the boot medium) that we don't want to give
# to the desktop user.
#
# The UID and GID for this user and group need to remain the same (respectively:
# 115 and 122) accross Tails releases: they are encoded numerically in ACLs
# which allow tails-persistence-setup to update persistence configuration
# files. If these UID and GID changed:
#  - when enabling a persistent volume, persistence configuration files
#    created with older Tails versions would be treated as unsafe and
#    thus disabled;
#  - tails-persistence-setup would not be allowed to modify persistence
#    configuration files created with an older Tails version.

echo "Creating the tails-persistence-setup user"

# If this fails because UID 115 or GID 122 are already in use,
# move the "stealer" user/group out of the way in 04-change-gids-and-uids.

addgroup --system --gid 122 tails-persistence-setup
adduser --system --uid 115 --gid 122 --no-create-home tails-persistence-setup
