#!/bin/sh

set -e

# Create the onioncircuits user.
#
# We run onioncircuits under this user, which has access to the
# filtered control port

echo "Creating the onioncircuits user"

adduser --system --quiet --group onioncircuits
