#!/bin/sh

set -e

# Create the onioncircuits user.
#
# We run onioncircuits under this user,
# which belongs to the debian-tor group.

echo "Creating the onioncircuits user"

adduser --system --quiet --group onioncircuits
adduser onioncircuits debian-tor
