#!/bin/sh

set -e

# Create the tor-monitor user.
#
# We run tor-monitor under this user,
# which belongs to the debian-tor group.

echo "Creating the tor-monitor user"

adduser --system --quiet --group tor-monitor
adduser tor-monitor debian-tor
