#!/bin/sh

set -e

# Create the tails-iuk-get-target-file user.
#
# The tails-iuk-get-target-file program may be run as this user.
# This allows us, some day, to allow it to run in the clear,
# without going through Tor.

echo "creating the tails-iuk-get-target-file user"

adduser --system --quiet --group --no-create-home tails-iuk-get-target-file
