#!/bin/sh

# Create the htp user.
#
# We run htpdate as this user, so that we can whitelist its
# non-Torified outgoing packets.

# Including common functions
. "${LH_BASE:-/usr/share/live-helper}"/scripts/build.sh

# Setting static variables
DESCRIPTION="$(Echo 'creating the htp user')"
HELP=""
USAGE="${PROGRAM}"

# Reading configuration files
Read_conffiles config/all config/common config/chroot
Set_defaults

Echo_message "creating the htp user"

adduser --system --quiet --group --no-create-home htp || :
