#!/bin/sh

# Create the ntpdate user.
#
# We run ntpdate as this user, so that we can whitelist its
# non-Torified outgoing packets.

# Including common functions
. "${LH_BASE:-/usr/share/live-helper}"/live-helper.sh

# Setting static variables
DESCRIPTION="$(Echo 'creating the ntpdate user')"
HELP=""
USAGE="${PROGRAM}"

# Reading configuration files
Read_conffiles config/all config/common config/chroot
Set_defaults

Echo_message "creating the ntpdate user"

adduser --system --quiet --group --no-create-home ntpdate || :
