#!/bin/sh

set -e

# Create the tor-launcher user.
#
# We run Tor Launcher under this user, and give it acces to Tor's
# control port via adding it to the debian-tor group.

echo "creating the tor-launcher user"

addgroup --system --quiet --gid 127 tor-launcher
adduser --system --quiet --uid 119 --gid 127 tor-launcher
adduser tor-launcher debian-tor
