#!/bin/sh

set -e

# Create the tails-upgrade-frontend user.
#
# The tails-upgrade-frontend program may be run as this user.
# This avoids having to grant the desktop user the right to install
# any arbitrary IUK.

echo "creating the tails-upgrade-frontend user"

adduser --system --quiet --group --no-create-home tails-upgrade-frontend
