#!/bin/sh

set -e

# Create the tails-update-frontend user.
#
# The tails-update-frontend program may be run as this user.
# This avoids having to grant the desktop user the right to install
# any arbitrary IUK.

echo "creating the tails-update-frontend user"

adduser --system --quiet --group --no-create-home tails-update-frontend
