#!/bin/sh

set -e

# Create the tails-persistence-setup user.
#
# The tails-persistence-setup program may be run as this user.
# This allows us to give it special privileges (e.g. access via udisk
# to internal disks and to the boot medium) that we don't want to give
# to the desktop user.

echo "creating the tails-persistence-setup user"

adduser --system --quiet --group --no-create-home tails-persistence-setup
