#!/bin/sh

set -e

# Create the tor-controlport-filter user.
#
# We run tor-controlport-filter under this user,
# which belongs to the debian-tor group.

echo "creating the tor-controlport-filter user"

adduser --system --quiet --group --no-create-home tor-controlport-filter
adduser tor-controlport-filter debian-tor
