#!/bin/sh

set -e

# Create the clear user.
#
# We run unsafe-browser under this user, so that we can whitelist its
# non-Torified outgoing packets.

echo "creating the clearnet user"

adduser --system --quiet --group clearnet
