#!/bin/sh

set -e

# Create the tails-install-iuk user.
#
# The tails-install-iuk program may be run as this user,
# which is granted some passwordless sudo credentials.

echo "creating the tails-install-iuk user"

adduser --system --quiet --group --no-create-home tails-install-iuk
adduser tails-install-iuk tails-iuk-get-target-file
