#!/bin/sh

set -e
set -u

echo "Installing Perl programs"

# Import ensure_hook_dependency_is_installed()
. /usr/local/lib/tails-shell-library/build.sh

ensure_hook_dependency_is_installed \
   cpanminus \
   libdist-zilla-perl \
   libdist-zilla-plugin-test-notabs-perl \
   libdist-zilla-plugin-test-perl-critic-perl

for dist in perl5lib iuk; do
   dist_dir="/usr/src/${dist}"
   cd "$dist_dir"
   PERL5LIB=/usr/src/perl5lib/lib PERL_CPANM_OPT=--notest dzil install
   cd
   rm -r "$dist_dir"
done
rm -r /root/.cpanm

# Satisfy the dependency of the tails-persistence-setup package
# on tails-perl5lib
install_fake_package tails-perl5lib 4.0

apt-get install --yes tails-persistence-setup

for patch in /usr/share/tails/build/run_t-p-s_as_its_dedicated_user.diff ; do
   (cd / && patch --forward --batch -p1 < "$patch")
   rm "$patch"
done
