#!/bin/sh

# Remove pdnsd's resolvconf hook.

# Including common functions
. "${LH_BASE:-/usr/share/live-helper}"/scripts/build.sh

# Setting static variables
DESCRIPTION="$(Echo 'removing pdnsd resolvconf hook')"
HELP=""
USAGE="${PROGRAM}"

# Reading configuration files
Read_conffiles config/all config/common config/chroot
Set_defaults

Echo_message "removing pdnsd resolvconf hook"

rm -f /etc/resolvconf/update.d/pdnsd
