#!/bin/sh

# Remove pidgin's (libpurple's) MSN support, that is affected by
# security issues far too often.

# Including common functions
. "${LH_BASE:-/usr/share/live-helper}"/scripts/build.sh

# Setting static variables
DESCRIPTION="$(Echo 'removing pidgin MSN support')"
HELP=""
USAGE="${PROGRAM}"

# Reading configuration files
Read_conffiles config/all config/common config/chroot
Set_defaults

Echo_message "removing pidgin MSN support"

dpkg -L libpurple0  | grep '/libmsn.so$' | xargs rm -f

