#!/bin/sh

set -e

# Remove pidgin's (libpurple's) sametime support, until CVE-2013-0273
# is fixed in the version of Debian Tails is built upon.

echo "removing pidgin sametime support"

dpkg -L libpurple0  | grep '/libsametime.so$' | xargs rm
