#!/bin/sh

set -e

# Remove pidgin's (libpurple's) mxit support, until CVE-2013-0272 and
# CVE-2013-0271 are fixed in the version of Debian Tails is built upon.

echo "removing pidgin mxit support"

dpkg -L libpurple0  | grep '/libmxit.so$' | xargs rm
