#!/bin/sh

set -e

# Remove pidgin's (libpurple's) MSN support, that is affected by
# security issues far too often.

echo "removing pidgin MSN support"

dpkg -L libpurple0  | grep '/libmsn.so$' | xargs rm
