#!/bin/sh

echo "installing backported Xorg"

apt-get --yes purge xserver-xorg-input-wacom
apt-get --yes install -t squeeze-backports \
   xorg \
   xserver-xorg \
   xserver-xorg-core \
   xserver-xorg-input-all \
   xserver-xorg-video-all \
   xserver-xorg-input-vmmouse/unstable \
   xserver-xorg-video-geode/unstable
apt-get --yes install -t squeeze-backports libgl1-mesa-dri libgl1-mesa-glx
