#!/bin/sh

echo "installing backported Xorg"

apt-get --yes install -t squeeze-backports \
   xorg \
   xserver-xorg \
   xserver-xorg-core \
   xserver-xorg-input-all \
   xserver-xorg-video-all \
   xserver-xorg-video-qxl
apt-get --yes install -t squeeze-backports libgl1-mesa-dri libgl1-mesa-glx \
   libglu1-mesa libdrm-radeon1
