#!/bin/sh

set -e

# Check whether the mimeapps list exists and has the expected content
grep -q "[Default Applications]" /etc/xdg/gnome-mimeapps.list

# Set the default application for TCRYPT containers
echo "application/x-tcrypt-container=gnome-disk-image-mounter.desktop" >> /etc/xdg/gnome-mimeapps.list
