#!/bin/sh

set -e

rm /usr/share/initramfs-tools/scripts/live-bottom/22sslcert
rm /usr/share/initramfs-tools/scripts/live-bottom/33enable_apport_crashes
rm /usr/share/initramfs-tools/scripts/live-bottom/34disable_kde_services
rm /usr/share/initramfs-tools/scripts/live-bottom/34disable_kpersonalizer
rm /usr/share/initramfs-tools/scripts/live-bottom/38jockey_disable_check
rm /usr/share/initramfs-tools/scripts/live-bottom/41apt_cdrom
