#!/bin/sh

rm -f /usr/share/initramfs-tools/scripts/live-bottom/22sslcert
rm -f /usr/share/initramfs-tools/scripts/live-bottom/33enable_apport_crashes
rm -f /usr/share/initramfs-tools/scripts/live-bottom/34disable_kde_services
rm -f /usr/share/initramfs-tools/scripts/live-bottom/34disable_kpersonalizer
rm -f /usr/share/initramfs-tools/scripts/live-bottom/38jockey_disable_check
rm -f /usr/share/initramfs-tools/scripts/live-bottom/41apt_cdrom
