#!/bin/sh

set -e
set -u

EXT="/usr/lib/thunderbird/extensions"

[ -d "$EXT" ] || exit 1

echo "Enabling Enigmail in Thunderbird"
ln -s /usr/share/xul-ext/enigmail "${EXT}/{847b3a00-7ab1-11d4-8f02-006008948af5}"
