#!/bin/sh

set -e

echo "Converting uBlock database dump into sqlite blob"

apt-get install --yes sqlite3

DUMP="/usr/share/tails/ublock-origin/ublock0.dump"
DATABASE="/etc/tor-browser/profile/extension-data/ublock0.sqlite"

mkdir -p "$(dirname "${DATABASE}")"

# The sed expression simply means: remove all CRLF ("\r\n"). The use
# of labels is simply to make this able to remove multiple CRLF to
# create a single (long) line. In the end, this restores the
# diff-friendly dump to the original sqlite dump.
sed ':a;N;$!ba;s_\r\n__g' "${DUMP}" | sqlite3 "${DATABASE}"

echo "Created uBlock sqlite blob successfully"

apt-get purge --yes sqlite3
