#!/bin/sh

# Compress the initramfs using a more size-wise efficient algorithm.

OPTS_FILE='/etc/initramfs-tools/initramfs.conf'

[ -f "${OPTS_FILE}" ] || exit 11

sed -i'' 's,^COMPRESS=.*,COMPRESS=lzma,' "${OPTS_FILE}"
