#!/bin/sh

set -e

echo "Configuring compression of the initramfs"

# Compress the initramfs using a more size-wise efficient algorithm.

OPTS_FILE='/etc/initramfs-tools/initramfs.conf'

[ -f "${OPTS_FILE}" ] || exit 11

sed -i'' 's,^COMPRESS=.*,COMPRESS=xz,' "${OPTS_FILE}"
