#!/bin/sh

set -e
set -u
set -x

echo "Setting up a build environment for kernel modules"

. /usr/share/tails/build/variables

# Import ensure_hook_dependency_is_installed()
. /usr/local/lib/tails-shell-library/build.sh

# Install gcc-8 and fake linux-compiler-gcc-9-x86
# (linux-headers-5.3.0+ depends on it, but Buster hasn't GCC 9)
ensure_hook_dependency_is_installed gcc-8
NEWEST_INSTALLED_KERNEL_VERSION="$(
    dpkg-query --showformat '${Version}\n' --show 'linux-image-*-amd64' \
    | sort --version-sort | tail -n1
)"
install_fake_package \
    linux-compiler-gcc-9-x86 \
    "${NEWEST_INSTALLED_KERNEL_VERSION}~0tails1"
ln -s /usr/bin/gcc-8 /usr/bin/gcc-9

ensure_hook_dependency_is_installed \
    build-essential \
    libelf-dev \
    "linux-headers-${KERNEL_VERSION}-amd64"
