#!/bin/sh

set -e
set -u
set -x

echo "Setting up a build environment for kernel modules"

. /usr/share/tails/build/variables

# Import ensure_hook_dependency_is_installed()
. /usr/local/lib/tails-shell-library/build.sh

# This hack is not needed on Buster but let's keep the commented code around
# for next time we need it.
#
# # Install gcc-6 and fake linux-compiler-gcc-8-x86
# # (linux-headers-4.19+ depends on it, but Stretch hasn't GCC 8)
# ensure_hook_dependency_is_installed gcc-6
# NEWEST_INSTALLED_KERNEL_VERSION="$(
#     dpkg-query --showformat '${Version}\n' --show 'linux-image-*-amd64' \
#     | sort --version-sort | tail -n1
# )"
# install_fake_package \
#     linux-compiler-gcc-8-x86 \
#     "${NEWEST_INSTALLED_KERNEL_VERSION}~0tails1"
# ln -s /usr/bin/gcc-6 /usr/bin/gcc-8

ensure_hook_dependency_is_installed \
    build-essential \
    libelf-dev \
    "linux-headers-${KERNEL_VERSION}-amd64"
