#!/bin/sh

set -e

# Remove unwanted browser search plugins.

echo "Removing unwanted browser search plugins"

# Import the TBB_INSTALL variable
. /usr/local/lib/tails-shell-library/tor-browser.sh

PLUGIN_DIR="${TBB_INSTALL}"/browser/searchplugins
rm "${PLUGIN_DIR}"/amazon*.xml
rm "${PLUGIN_DIR}"/bing*.xml
rm "${PLUGIN_DIR}"/eBay*.xml
rm "${PLUGIN_DIR}"/yahoo*.xml
