#!/bin/sh

set -e

# Remove unwanted iceweasel search plugins.

echo "Removing unwanted iceweasel search plugins"

rm /etc/iceweasel/searchplugins/common/duckduckgo.xml
rm /etc/iceweasel/searchplugins/locale/*/amazon*.xml
rm /etc/iceweasel/searchplugins/locale/*/answers.xml
rm /etc/iceweasel/searchplugins/locale/*/bing*.xml
rm /etc/iceweasel/searchplugins/locale/*/eBay*.xml
rm /etc/iceweasel/searchplugins/locale/*/yahoo*.xml
