#!/bin/sh

# Remove unwanted iceweasel search plugins.

# Including common functions
. "${LH_BASE:-/usr/share/live-helper}"/scripts/build.sh

# Setting static variables
DESCRIPTION="$(Echo 'removing unwanted iceweasel search plugins')"
HELP=""
USAGE="${PROGRAM}"

# Reading configuration files
Read_conffiles config/all config/common config/chroot
Set_defaults

Echo_message "removing unwanted iceweasel search plugins"

UNWANTED_SEARCHPLUGINS='amazondotcom answers eBay yahoo'
for plugin in $UNWANTED_SEARCHPLUGINS ; do
   rm -f /usr/share/iceweasel/searchplugins/${plugin}.xml
done
