#!/bin/sh

# Remove unwanted iceweasel search plugins.

echo "removing unwanted iceweasel search plugins"

rm -f /etc/iceweasel/searchplugins/common/duckduckgo.xml
rm -f /etc/iceweasel/searchplugins/locale/*/amazon*.xml
rm -f /etc/iceweasel/searchplugins/locale/*/answers.xml
rm -f /etc/iceweasel/searchplugins/locale/*/bing*.xml
rm -f /etc/iceweasel/searchplugins/locale/*/eBay*.xml
rm -f /etc/iceweasel/searchplugins/locale/*/yahoo*.xml
