#!/bin/sh

set -e

echo "Overriding TBB branding with our own"

install --owner root --group root --mode 0755 --directory /etc/xul-ext
install --owner root --group root --mode 0644 \
   /etc/iceweasel/profile/extensions/branding@amnesia.boum.org/defaults/preferences/prefs.js \
   /etc/xul-ext/torbutton.js
