#!/bin/sh

echo "Generating Tor Browser profile"

# Generate Tor Browser profile at build time so it won't reside in RAM

set -e

/usr/local/bin/generate-tor-browser-profile
mv ~/.tor-browser /etc/skel
