#! /bin/sh

set -e
set -u

echo "Set up greeter language codes"

# Extract language codes from the supported locales
grep -E ".+_[^.@]+ " /usr/share/i18n/SUPPORTED | \
    awk '{print $1;}' | \
    uniq > /usr/share/tails-greeter/language_codes
