#!/bin/sh

# i2p should not start per default. At some point we might want this script to
# start during init if so selected in the boot options, but ATM users have to
# start the script manually.

update-rc.d -f i2p remove
