#!/bin/sh

set -e

echo "Installing AppArmor profiles for Tor Browser"

# Import ensure_hook_dependency_is_installed()
. /usr/local/lib/tails-shell-library/build.sh

ensure_hook_dependency_is_installed patch

PATCH='/usr/share/tails/torbrowser-AppArmor-profile.patch'

### Functions

toggle_src_APT_sources() {
   MODE="$1"
   TEMP_APT_SOURCES='/etc/apt/sources.list.d/tmp-deb-src.list'

   case "$MODE" in
      on)
         cat /etc/apt/sources.list /etc/apt/sources.list.d/*.list \
            | grep --extended-regexp --invert-match \
                 'file:/root/local-packages' \
            | grep --extended-regexp --invert-match \
                 '^deb\s+http://tagged\.snapshots\.deb\.tails\.boum.org/[^/]+/torproject(/|\s)' \
            | grep --extended-regexp --invert-match \
                 '^deb\s+http://time-based\.snapshots\.deb\.tails\.boum.org/torproject/' \
            | sed --regexp-extended -e 's,^deb(\s+),deb-src\1,' \
            > "$TEMP_APT_SOURCES"
         ;;
      off)
         rm "$TEMP_APT_SOURCES"
         ;;
   esac

   apt-get --yes update
}

install_torbrowser_AppArmor_profiles() {
   tmpdir="$(mktemp -d)"
   (
      cd "$tmpdir"
      apt-get source torbrowser-launcher/sid
      install -m 0644 \
              torbrowser-launcher-*/apparmor/torbrowser.Browser.* \
              /etc/apparmor.d/
      install -m 0644 \
              torbrowser-launcher-*/apparmor/tunables/* \
              /etc/apparmor.d/tunables/
   )
   rm -r "$tmpdir"
}

### Main

toggle_src_APT_sources on
install_torbrowser_AppArmor_profiles
toggle_src_APT_sources off
(cd / && patch --forward --batch -p1 < "$PATCH")
rm "$PATCH"
