#!/bin/sh

set -e

# Update the system dconf databases so that /etc/dconf/db/local.d is
# taken into account.

echo "Updating the system DConf databases"

# Import ensure_hook_dependency_is_installed()
. /usr/local/lib/tails-shell-library/build.sh

ensure_hook_dependency_is_installed dconf-cli

dconf update
chmod 0644 /etc/dconf/db/local
