#! /bin/sh

set -e
set -u

echo "Configure Enigmail's version"

# Import set_mozilla_pref()
. /usr/local/lib/tails-shell-library/tor-browser.sh

# Rationale: the only way to suppress Enigmail's "first run" wizard is
# to have *some* version configured. But too old versions might
# trigger work-around code to run unnecessarily.
version="$(dpkg-query --show \
                      --showformat='${source:Upstream-Version}' \
                      enigmail)"
set_mozilla_pref /etc/xul-ext/enigmail.js \
                 extensions.enigmail.configuredVersion \
                 "\"${version}\""
