#!/bin/sh

set -e

# Load GConf settings.

echo "Loading GConf settings"

gct() {
	gconftool-2 \
	   --direct \
	   --config-source xml:readwrite:/etc/gconf/gconf.xml.defaults \
	   "${@}"
}

for file in /usr/share/amnesia/gconf/*.xml ; do
	gct --load "${file}"
done
