#!/bin/sh

# Lenny's apt-get lacks an autoremove command, let's use aptitude to
# get rid of needless dependencies.
aptitude --assume-yes purge \
   epiphany-browser epiphany-browser-data epiphany-extensions epiphany-gecko
