#!/bin/sh

set -e

echo "Creating prefs override for Tor Launcher"

# Import the TOR_LAUNCHER_INSTALL variable.
. /usr/local/lib/tails-shell-library/tor-browser.sh

ln -s /etc/xul-ext/tor-launcher.js \
      "${TOR_LAUNCHER_INSTALL}/defaults/preferences/000system.js"
