#!/bin/sh

set -e

echo "Setting GDM background"

# The gdm3 initscript updates /var/lib/gdm3/.gconf.mandatory/ at
# runtime from files in /usr/share/gdm/greeter-config/ => let's remove
# the file that deals with background pictures, so that tails-greeter
# gets the less flashy default background that's already used in the
# desktop session.

rm /usr/share/gdm/greeter-config/10_desktop-base
