#!/bin/sh

set -e

echo "Making GDM *not* restart automatically"

# The GDM unit file has a Restart=always directive, which is good in the
# general case. However, it breaks our emergency shutdown on boot medium
# removal feature. Let's disable it, then.

perl -pi -E 's{^Restart=.*$}{Restart=no}' /lib/systemd/system/gdm.service
