#!/bin/sh

set -e

# Install Plymouth (in lb 2.x, the "standard" packages list pulls
# console-common in, which plymouth conflicts with, so we have to deal
# with that at this stage.)

echo "Installing Plymouth"

apt-get --yes purge console-common
apt-get --yes install plymouth
