#!/bin/sh

set -e
set -u

echo "Install Electrum"

# Import install_fake_package
. /usr/local/lib/tails-shell-library/build.sh

REAL_PKG_VERSION=$(dpkg-query -W -f='${Version}\n' python3-qdarkstyle)
FAKE_PKG_VERSION=${REAL_PKG_VERSION}+tails.fake1
install_fake_package python3-qdarkstyle "${FAKE_PKG_VERSION}" python
