#!/bin/sh
set -e
set -u
echo "Explicitly disable Wayland in GDM, and adjust permissions accordingly"
sed --in-place --regexp-extended \
    's/^#WaylandEnable=false$/WaylandEnable=false/' /etc/gdm3/daemon.conf

# rootless X.Org may require access to /dev/fb0, that's owned by root:video
adduser Debian-gdm video
