#!/bin/sh

set -e
set -u

ORIG_SHELL_DESKTOP_FILE="/usr/share/applications/org.gnome.Shell.desktop"
TAILS_SHELL_DESKTOP_FILE="/usr/share/gdm/greeter/applications/gdm-shell-tails.desktop"

ORIG_SESSION_FILE="/usr/share/gnome-session/sessions/gnome-classic.session"
TAILS_SESSION_FILE="/usr/share/gnome-session/sessions/gdm-tails.session"

create_gdm_shell_tails_desktop_file() {
    if ! grep -q --fixed-strings --line-regexp "Exec=/usr/bin/gnome-shell" \
            "${ORIG_SHELL_DESKTOP_FILE}"; then
        echo "Couldn't find expected exec line in GNOME Shell's .desktop file"
        exit 1
    fi
    sed "s,^Exec=/usr/bin/gnome-shell$,Exec=/usr/bin/gnome-shell --mode=gdm-tails," \
        "${ORIG_SHELL_DESKTOP_FILE}" \
        > "${TAILS_SHELL_DESKTOP_FILE}"
}

create_tails_session_file() {
    install -D "${ORIG_SESSION_FILE}" "${TAILS_SESSION_FILE}"
    if ! grep -q -E \
            "^RequiredComponents=org\.gnome\.Shell" "${TAILS_SESSION_FILE}" || \
       ! grep -q --fixed-strings --line-regexp \
            "Name=GNOME Classic" "${TAILS_SESSION_FILE}"; then
        echo "Couldn't find expected exec line in GNOME's session file"
        exit 1
    fi
    sed -i "s,^RequiredComponents=org\.gnome\.Shell,RequiredComponents=gdm-shell-tails;tails-greeter," "${TAILS_SESSION_FILE}"
    sed -i "s,^Name=GNOME Classic$,Name=Display Manager," "${TAILS_SESSION_FILE}"
    # Remove translations of the name
    sed -i "/^Name\[/d" "${TAILS_SESSION_FILE}"
}

create_gdm_shell_tails_desktop_file
create_tails_session_file
