#!/bin/sh

# Including common functions
. "${LH_BASE:-/usr/share/live-helper}"/functions.sh

# Setting static variables
DESCRIPTION="$(Echo 'add modules to /etc/modules')"
HELP=""
USAGE="${PROGRAM}"

# Reading configuration files
Read_conffiles config/all config/common config/chroot
Set_defaults

Echo_message "Adding cpufreq modules to /etc/modules"
echo 'acpi-cpufreq' > /etc/modules
echo 'cpufreq_powersave' > /etc/modules
echo 'cpufreq_ondemand' > /etc/modules
