#!/bin/sh

# Disable ssh-agent in /etc/X11/Xsession.options
# (seahorse / gnome-keyring are more user-friendly)

# Including common functions
. "${LH_BASE:-/usr/share/live-helper}"/scripts/build.sh

# Setting static variables
DESCRIPTION="$(Echo 'disabling ssh-agent')"
HELP=""
USAGE="${PROGRAM}"

# Reading configuration files
Read_conffiles config/all config/common config/chroot
Set_defaults

Echo_message "disabling ssh-agent"

OPTS_FILE='/etc/X11/Xsession.options'

[ -f "${OPTS_FILE}" ] || exit 11

sed -i'' 's,^use-ssh-agent,#use-ssh-agent,' "${OPTS_FILE}"
