#!/bin/sh

set -e

# Move any /usr/bin/tsocks installed by any package out of the way,
# now (--rename) as well for any future one (hint: apt-get upgrade...).
dpkg-divert --rename --add /usr/bin/tsocks
