#!/bin/sh

set -eu

echo "Wrapping gdm-x-session to give feedback to the user when X.Org cannot start"

dpkg-divert --add --rename --divert \
            /usr/lib/gdm3/gdm-x-session.real \
	    /usr/lib/gdm3/gdm-x-session

ln -s /usr/lib/gdm3/gdm-x-session.tails /usr/lib/gdm3/gdm-x-session
