#!/bin/sh

set -e

echo "Configuring htpdate HTTP User-Agent"

CONFFILE='/etc/default/htpdate.user-agent'

install -o root -g root -m 0644 /dev/null "$CONFFILE"

echo "HTTP_USER_AGENT=\"$(/usr/local/lib/getTorBrowserUserAgent)\"" \
     > "$CONFFILE"
