#!/bin/sh

set -e

echo "Tweaking AppArmor profiles"

# Pass all profiles the attach_disconnected flag,
# that's needed for compatibility with overlayfs (#9045)
find /etc/apparmor.d/ -maxdepth 1 -type f \
     -exec perl -pi -E 's,([a-z]+\s+){,$1flags=(attach_disconnected) {,' '{}' \;

# Also pass the attach_disconnected flag to the Tor Browser profile,
# because the above regex doesn't match that one.
perl -pi -E 's,(profile.*\s+){,$1flags=(attach_disconnected) {,' /etc/apparmor.d/torbrowser.Browser.firefox
