#!/bin/sh

set -e
set -u

echo "Building dkms modules"

. /usr/share/amnesia/build/variables

# the -dkms package must be installed *after* dkms to be properly registered
apt-get install --yes build-essential dkms

# Installing the headers triggers the building of the modules for that kernel
apt-get install --yes \
    "linux-headers-${KERNEL_VERSION}-amd64" \
    virtualbox-guest-dkms

# clean the build directory
# rm -r /var/lib/dkms/virtualbox-guest/

# virtualbox-guest-dkms's postrm script deletes any previously
# built binary module; let's delete it before the package gets purged.
rm /var/lib/dpkg/info/virtualbox-guest-dkms.prerm

# Also copy the udev rules installed by virtualbox-guest-dkms to enable guest
# additions by default.
cp -a /lib/udev/rules.d/60-virtualbox-guest-dkms.rules /etc/udev/rules.d/
