#!/bin/sh

set -e

# Fix up: tails-installer-launcher still exists in Tails Installer
# 4.4.19 but we don't need the splash screen any more (#8859).

echo "Fixing tails-installer-launcher"

rm /usr/bin/tails-installer-launcher
ln -s /usr/lib/tails_installer/tails-installer \
      /usr/bin/tails-installer-launcher
