#!/bin/sh

# Install modules managed by module-assistant

# Including common functions
. "${LH_BASE:-/usr/share/live-helper}"/live-helper.sh

# Setting static variables
DESCRIPTION="$(Echo 'installing modules managed by module-assistant')"
HELP=""
USAGE="${PROGRAM}"

# Get LH_DISTRIBUTION
Read_conffiles config/bootstrap
Set_defaults

Echo_message "installing modules managed by module-assistant"

case "${LH_DISTRIBUTION}" in
   lenny)
      MODULES="broadcom-sta-source rt2570-source rt2860-source"
      ;;
   *)
      # rt2570 and rt2860 are supported by Squeeze's kernel
      MODULES="broadcom-sta-source"
      ;;
esac

MA="module-assistant --text-mode --non-inter"

apt-get install --yes build-essential module-assistant debhelper
$MA update

for MODULE in $MODULES ; do
   for KERNEL in /boot/vmlinuz-* ; do
      VERSION="$(basename ${KERNEL} | sed -e 's|vmlinuz-||')"
      $MA --quiet auto-install ${MODULE} -l ${VERSION}
   done
   $MA clean ${MODULE}
   aptitude --assume-yes purge ${MODULE}
done
