#!/bin/sh

# Install modules managed by module-assistant

# Including common functions
. "${LH_BASE:-/usr/share/live-helper}"/scripts/build.sh

# Setting static variables
DESCRIPTION="$(Echo 'installing modules managed by module-assistant')"
HELP=""
USAGE="${PROGRAM}"

Set_defaults

Echo_message "installing modules managed by module-assistant"

MODULES=""
MA="module-assistant --text-mode --non-inter"

apt-get install --yes build-essential module-assistant debhelper
$MA update

for MODULE in $MODULES ; do
   for KERNEL in /boot/vmlinuz-* ; do
      VERSION="$(basename ${KERNEL} | sed -e 's|vmlinuz-||')"
      $MA --quiet auto-install ${MODULE} -l ${VERSION}
   done
   $MA clean ${MODULE}
   aptitude --assume-yes purge ${MODULE}
done

rm -f /usr/src/*.deb
