#!/bin/sh

set -e

# Install modules managed by module-assistant

echo "installing modules managed by module-assistant"
MODULES=""
MA="module-assistant --text-mode --non-inter"

ma_install_tools ()
{
   apt-get install --yes build-essential module-assistant debhelper
   $MA update
}

ma_install_modules ()
{
   for MODULE in $@ ; do
      for KERNEL in /boot/vmlinuz-* ; do
	 VERSION="$(basename ${KERNEL} | sed -e 's|vmlinuz-||')"
	 echo "module-assistant: installing module ${MODULE} for kernel ${VERSION}"
	 $MA --quiet auto-install ${MODULE} -l ${VERSION}
      done
      $MA clean ${MODULE}
      apt-get --yes purge ${MODULE}
   done
}

ma_cleanup ()
{
   rm -f /usr/src/*.deb
}

if [ -n "${MODULES}" ] ; then
   ma_install_tools
   ma_install_modules ${MODULES}
   ma_cleanup
fi

