#!/bin/sh

# Install ralink rt2570 drivers

apt-get install --yes build-essential

type module-assistant || apt-get install --yes module-assistant
module-assistant update

for KERNEL in /boot/vmlinuz-*
do
	VERSION="$(basename ${KERNEL} | sed -e 's|vmlinuz-||')"

	module-assistant --non-inter --quiet auto-install rt2570-source -l ${VERSION}
done

module-assistant clean rt2570-source

aptitude --purge remove rt2570-source
