#!/bin/sh

set -e

echo "Registering menus"

for app in liveusb-creator-launcher tails-persistence-delete tails-persistence-setup tails-updater ; do
   xdg-desktop-menu install --novendor \
      /usr/share/desktop-directories/Tails.directory \
      "/usr/share/applications/${app}.desktop"
done

xdg-desktop-menu forceupdate
