#!/bin/sh

set -e

echo "Registering and tweaking menus"

# Import ensure_hook_dependency_is_installed()
. /usr/local/lib/tails-shell-library/build.sh

ensure_hook_dependency_is_installed xdg-utils

for app in tails-installer tails-persistence-delete tails-persistence-setup tails-about tails-documentation; do
   xdg-desktop-menu install --novendor \
      /usr/share/desktop-directories/Tails.directory \
      "/usr/share/applications/${app}.desktop"
done

rm \
   /usr/share/applications/gnome-online-accounts-panel.desktop \
   /usr/share/applications/laptop-mode-tools.desktop \
   /usr/share/applications/sniff.desktop

sed -i'' --regexp-extended 's,^Exec=pidgin$,Exec=/usr/local/bin/pidgin,' \
   /usr/share/applications/pidgin.desktop

# Run OpenPGP Applet automatically, but do not show it in the Applications menu
rm /etc/xdg/autostart/openpgp-applet.desktop
mv /usr/share/applications/openpgp-applet.desktop \
   /etc/xdg/autostart/

xdg-desktop-menu forceupdate
