#!/bin/sh

set -e

echo "Creating system-wide Tails GnuPG keyring"

apt-get --yes install faketime
faketime "$(date -d '@$SOURCE_DATE_EPOCH')" \
   gpg --batch --no-default-keyring \
       --keyring /usr/share/keyrings/tails-keyring.gpg \
       --import /usr/share/doc/tails/website/*.key
apt-get --yes purge faketime '^libfaketime*'

chmod a+r /usr/share/keyrings/tails-keyring.gpg
