#!/bin/sh

set -e

echo "Creating system-wide Tails GnuPG keyring"

# Import faketime_sde_wrapper()
. /usr/local/lib/tails-shell-library/build.sh

faketime_sde_wrapper \
   gpg --batch --no-default-keyring \
       --keyring /usr/share/keyrings/tails-keyring.gpg \
       --import /usr/share/doc/tails/website/*.key

chmod a+r /usr/share/keyrings/tails-keyring.gpg
