#!/bin/sh

set -e

echo "Creating system-wide Tails GnuPG keyring"

gpg --batch --no-default-keyring --keyring /usr/share/keyrings/tails-keyring.gpg --import /usr/share/doc/tails/website/*.key
chmod a+r /usr/share/keyrings/tails-keyring.gpg
