#!/bin/sh

set -e

echo "Creating CA bundle for authenticating https://tails.boum.org/"

BUNDLE=/usr/local/etc/ssl/certs/tails.boum.org-CA.pem

mkdir -p $(dirname "${BUNDLE}")

cat \
   ### XXX: remove this after 2021-02-12
   /usr/share/tails/certs/Lets-Encrypt-Authority-X3.pem \
   ### Last updated: 2021-01-19
   # References:
   #  - https://letsencrypt.org/certificates/
   #  - https://letsencrypt.org/2020/09/17/new-root-and-intermediates.html
   # RSA 2048, active
   /usr/share/tails/certs/lets-encrypt-r3.pem \
   # RSA 2048, backup
   /usr/share/tails/certs/lets-encrypt-r4.pem \
   # ECDSA P-384, upcoming
   /usr/share/tails/certs/lets-encrypt-e1.pem \
   # ECDSA P-384, upcoming backup
   /usr/share/tails/certs/lets-encrypt-e2.pem \
   > "$BUNDLE"

chmod a+r "$BUNDLE"

rm \
   /usr/share/tails/certs/Lets-Encrypt-Authority-X3.pem \
   /usr/share/tails/certs/lets-encrypt-*.pem
