#!/bin/sh

set -e

echo "Creating Tails Upgrader's CA bundle"

BUNDLE=/usr/local/etc/ssl/certs/tails-iuk.pem

cat /etc/ssl/certs/AddTrust_External_Root.pem \
    /etc/ssl/certs/UTN_USERFirst_Hardware_Root_CA.pem \
   > "$BUNDLE"

chmod a+r "$BUNDLE"
