#!/bin/sh

set -e

echo "Creating CA bundle for authenticating https://tails.boum.org/"

BUNDLE=/usr/local/etc/ssl/certs/tails.boum.org-CA.pem

cat /etc/ssl/certs/AddTrust_External_Root.pem \
   > "$BUNDLE"

chmod a+r "$BUNDLE"
