#!/bin/sh

set -eu

echo "Configuring file associations"

defaults_file=/etc/gnome/defaults.list

if grep -E '^application/pgp-keys=' "$defaults_file"; then
    echo "application/pgp-keys is already configured in $defaults_file" >&2
    exit 1
else
   # XXX: Stretch -- this fixes https://bugs.freedesktop.org/show_bug.cgi?id=93656
   # (Tails#10889, Tails#10571)
   echo 'application/pgp-keys=seahorse-pgp-keys.desktop' \
	>> "$defaults_file"
   echo 'application/x-iwork-keynote-sffkey=seahorse-pgp-keys.desktop' \
	>> "$defaults_file"
fi
