#!/bin/sh
set -e
set -u

echo "Installing libdvd-pkg"

apt-get --yes install libdvd-pkg
dpkg-reconfigure libdvd-pkg

# Create and install fake libdvd-pkg package
(
    local tmp
    tmp="$(mktemp -d)"
    apt-get install --yes equivs

    LIBDVD_PKG_VERSION=$(dpkg-query -s libdvd-pkg | grep Version | cut -d ' ' -f2 )

    cat > "${tmp}/libdvd-pkg-${LIBDVD_PKG_VERSION}.control" << EOF
Section: multimedia
Priority: optional
Homepage: https://tails.boum.org/
Standards-Version: 3.6.2

Package: libdvd-pkg-${LIBDVD_PKG_VERSION}
Maintainer: Tails developers <amnesia@boum.org>
Provides: libdvd-pkg
Architecture: all
Description: (Fake) libdvd-pkg package
 Provide placeholder to keep libdvdcss2 happy.
EOF

    cd "${tmp}"
    equivs-build "${tmp}/libdvd-pkg-${LIBDVD_PKG_VERSION}.control"
    dpkg -i "${tmp}/libdvd-pkg-${LIBDVD_PKG_VERSION}_1.0_all.deb"
    cd -
    rm -R "${tmp}"
)
