#!/bin/sh

set -e

# Append some version information to /etc/amnesia/version

echo "Appending some version information to /etc/amnesia/version"

echo "live-boot: `dpkg-query -W -f='${Version}\n' live-boot`" \
   >> /etc/amnesia/version

echo "live-config: `dpkg-query -W -f='${Version}\n' live-config`" \
   >> /etc/amnesia/version
