#!/bin/sh

set -u
set -e

# Everything moved by this hook script will be reversed in the event that
# the string "i2p" is entered at a boot prompt

DEST="/usr/share/tails"

[ -d "/usr/share/i2p" ] || return 0

mv -f /usr/share/i2p "$DEST"
mv -f /usr/sbin/wrapper "$DEST/i2p"
mv -f /usr/share/applications/i2p.desktop "$DEST/i2p"
