#!/bin/sh

set -e

echo "Removing unwanted packages"

### Deinstall dev packages.

# We use apt-get as aptitude doesn't know about globs.
# There are packages we could be tempted to remove but we can't:
#   - gcc-4.7-base (libstdc++6 depends on it)
#   - libgcc1 (vidalia depends on it)
#   - cpp, cpp-4.4 (big parts of GNOME depend on it)
apt-get --yes purge  \
   '^linux-kbuild-*' \
   '^linux-headers-*' \
   build-essential debhelper dkms dpatch dpkg-dev \
   gcc gcc-4.7 gcc-4.8 \
   intltool-debian \
   libc6-dev libgl1-mesa-dev libstdc++6-4.4-dev linux-libc-dev \
   make \
   module-assistant \
   po-debconf \
   equivs virtualbox-guest-dkms

### Deinstall a few unwanted packages that were pulled by tasksel
### since they have Priority: standard.
apt-get --yes purge  \
   apt-listchanges at bsd-mailx dc debian-faq doc-debian dselect \
   '^exim4*' ftp m4 mlocate mutt ncurses-term nfs-common portmap procmail python-apt \
   python-reportbug reportbug telnet texinfo time w3m wamerican

### Deinstall some other unwanted packages.
apt-get --yes purge  \
    '^aptitude*' \
    db5.1-util \
    krb5-locales \
    live-build \
    locales \
    '^openssh-blacklist*' \
    python2.6 \
    python2.6-minimal \
    rpcbind \
    tasksel \
    tasksel-data \

### Deinstall dependencies of the just removed packages.
apt-get --yes --purge autoremove
