#!/bin/sh

set -e

echo "Removing unwanted files"

# Get POTFILES_DOT_IN
. /usr/share/amnesia/build/variables

find /usr/share/doc -type f -name changelog.gz        -delete
find /usr/share/doc -type f -name changelog.Debian.gz -delete
find /usr/share/doc -type f -name NEWS.Debian.gz      -delete

# Remove .in files managed by intltool
rm $POTFILES_DOT_IN
