#!/bin/sh

set -e

echo "Removing unwanted files"

rm /usr/share/icons/gnome/icon-theme.cache

rm -r \
   /usr/share/inkscape/examples \
   /usr/share/inkscape/tutorials

# Ease transition to "stop shipping bugs/ and todo/ in ISO images"
# This is for people who have a too-clever caching build setup that
# goes on shipping files foverer as long as it has built them once.
rm -rf /usr/share/doc/tails/website/bugs/                   \
       /usr/share/doc/tails/website/todo/                   \
       /usr/share/doc/tails/website/bugs.html               \
       /usr/share/doc/tails/website/todo.html               \
       /usr/share/doc/tails/website/wishlist.html           \
       /usr/share/doc/tails/website/contribute/roadmap.html

find /usr/share/doc -type f -name changelog.gz -exec rm "{}" \;
find /usr/share/doc -type f -name changelog.Debian.gz -exec rm "{}" \;
find /usr/share/doc -type f -name NEWS.Debian.gz -exec rm "{}" \;

rm -rf /tmp/*
find /usr -name "*.pyc" -print0 | xargs -0r rm -f

# truncate logs
for file in $(find /var/log/ -type f); do
	: > "${file}"
done
