#!/bin/sh

echo "Removing unwanted files"

rm -rf \
   /usr/share/inkscape/examples \
   /usr/share/inkscape/tutorials

find /usr/share/doc -type f -name changelog.gz -exec rm "{}" \;
find /usr/share/doc -type f -name changelog.Debian.gz -exec rm "{}" \;
