#!/bin/sh

set -e

echo "Removing unwanted packages"

### Deinstall dev packages.

# We use apt-get as aptitude doesn't know about globs.
# There are packages we could be tempted to remove but we can't:
#   - gcc-*-base (libstdc++6 depends on it)
#   - libgcc1 (apt depends on it)
#   - cpp, cpp-* (big parts of GNOME depend on it)
apt-get --yes purge  \
   '^linux-compiler-*' \
   '^linux-kbuild-*' \
   debhelper dpkg-dev \
   gcc gcc-6 \
   intltool-debian \
   libc6-dev \
   libelf-dev \
   linux-libc-dev \
   make \
   po-debconf \
   rsyslog \
   libdvdcss-dev

### Deinstall a few unwanted packages that were pulled by tasksel
### since they have Priority: standard.
apt-get --yes purge  \
   '^exim4*' \
   m4 \
   mlocate \
   nfs-common \
   procmail \
   texinfo

### Deinstall some other unwanted packages.
apt-get --yes purge  \
    '^aptitude*' \
    '^geoclue*' \
    libdvdcss2-dbgsym \
    live-build \
    rpcbind \
    tasksel \
    tasksel-data \
    tcpd

### Deinstall dependencies of the just removed packages.
apt-get --yes --purge autoremove
