#!/bin/sh

set -e

echo "Disabling multiarch in APT"

# Note that we cannot do "dpkg --remove-architecture amd64"
# as we have amd64 packages installed, that we want to keep.

echo 'APT::Architectures {"i386";};' \
     > /etc/apt/apt.conf.d/13architectures
