#!/bin/sh

set -e

echo "Setting correct file permissions"

chmod 00440 /etc/sudoers.d/*

# NetworkManager requires these permissions
chmod 00600 /etc/NetworkManager/system-connections/*

# For persistent Tor settings via Tor Launcher, the debian-tor user
# must be able to write into `/etc/tor`.
chown -R debian-tor:debian-tor /etc/tor
