#!/bin/sh

set -e

# Make IUKs smaller
echo "Setting mtime on large files whose content generally do not change"
touch -t 197001010000 \
   /usr/lib/locale/locale-archive \
   /usr/share/ppd/hplip/HP/*.ppd  \
   /var/lib/anthy/anthy.dic       \
   /var/lib/anthy/mkworddic/anthy.wdic
