#!/bin/sh

set -e

cat > /etc/apt/apt.conf.d/0000runtime-proxy <<EOF
// Proxy through Polipo to torify outgoing APT HTTP connections.
// This setting must be overriden at build time by live-build's
// 00http-proxy configuration file.
// That's why it is created in a chroot local hook.

Acquire::http::Proxy "http://127.0.0.1:8118/";
EOF
