#!/bin/sh

set -eu

echo "Configuring APT for runtime"

# Replace http:// with tor+http:// in APT sources
perl -p -i \
     -E 's,\A ((?:\#)? \s* deb(?:-src)? \s+)http://,$1tor+http://,xms' \
     /etc/apt/sources.list /etc/apt/sources.list.d/*.list
