#!/bin/sh

# Exit if lo interface
[ "$METHOD" = "loopback" ] && exit 0

IPTABLES_RULES=/etc/firewall.conf

[ -x /sbin/iptables-restore ]	|| exit 2
[ -n "$IPTABLES_RULES" ]	|| exit 3
[ -r "$IPTABLES_RULES" ]	|| exit 4

/sbin/iptables-restore < "$IPTABLES_RULES"
