#!/bin/sh

# set -x

. config/amnesia
if [ -e config/amnesia.local ] ; then
   . config/amnesia.local
fi

# a clean starting point
rm -rf cache/stages_rootfs

# get LH_LANGUAGE
. config/chroot
# get LH_ARCHITECTURE
. config/bootstrap

# build the doc wiki
./build-wiki
if [ -r config/binary_local-includes/doc/amnesia/wiki/index.${LH_LANGUAGE}.html ]; then
   cp config/binary_local-includes/doc/amnesia/wiki/index.${LH_LANGUAGE}.html \
      config/binary_local-includes/doc/amnesia/wiki/index.html
else
   cp config/binary_local-includes/doc/amnesia/wiki/index.en.html \
      config/binary_local-includes/doc/amnesia/wiki/index.html
fi

# fix permissions on {binary,chroot}_local-includes; they may be
# wrong, e.g. if the tarball was extracted with a strict umask
chmod -R go+rX config/binary_local-includes/
chmod -R go+rX config/chroot_local-includes/etc
chmod 0755 config/chroot_local-includes/home
chmod 0700 config/chroot_local-includes/home/amnesia
chmod -R go+rX config/chroot_local-includes/usr
chmod -R go+rx config/chroot_local-includes/usr/local/bin
chmod -R go+rx config/chroot_local-includes/usr/local/sbin

# build all configured image types
for BUILD_TYPE in ${AMNESIA_IMAGES} ; do

   case "$BUILD_TYPE" in
      iso)
	 BUILD_FILENAME_EXT=iso
	 BUILD_FILENAME=binary
	 ;;
      tar)
	 BUILD_FILENAME_EXT=tar.gz
	 BUILD_FILENAME=binary-tar
	 ;;
      usb-hdd)
	 BUILD_FILENAME_EXT=img
	 BUILD_FILENAME=binary
	 ;;
      *)
	 echo "Image type ${BUILD_TYPE} is not supported." >&2
	 exit 1
	 ;;
   esac
   BUILD_BASENAME="amnesia-${LH_ARCHITECTURE}-${AMNESIA_BASE}-${LH_LANGUAGE}-${AMNESIA_VERSION}-${AMNESIA_TODAY}"
   BUILD_DEST_FILENAME="${BUILD_BASENAME}.${BUILD_FILENAME_EXT}"
   BUILD_MANIFEST="${BUILD_DEST_FILENAME}.list"
   BUILD_PACKAGES="${BUILD_DEST_FILENAME}.packages"
   BUILD_LOG="${BUILD_DEST_FILENAME}.buildlog"

   echo "Cleaning binary stage..."
   lh clean noautoconfig --binary
      
   echo "Running lh config..."
   lh config noautoconfig --binary-images "${BUILD_TYPE}"

   echo "Building $BUILD_TYPE image ${BUILD_BASENAME}..."
   if lh build noautoconfig ${@} 2>&1 | tee "${BUILD_LOG}" ; then
      echo "Image was successfully created, moving it to ${BUILD_DEST_FILENAME}"
      mv -i "${BUILD_FILENAME}.${BUILD_FILENAME_EXT}" "${BUILD_DEST_FILENAME}"
      mv -i "${BUILD_FILENAME}.list" "${BUILD_MANIFEST}"
      mv -i "${BUILD_FILENAME}.packages" "${BUILD_PACKAGES}"
   else
      echo "lh build failed." >&2
      exit 1
   fi

done
