#! /bin/sh
# automatically run by lh_config

. config/amnesia
if [ -e config/amnesia.local ] ; then
   . config/amnesia.local
fi

# init variables
RUN_LH_CONFIG="lh config noautoconfig"

# init config/ with defaults
$RUN_LH_CONFIG ${@}

# set Amnesia's general options
$RUN_LH_CONFIG \
   --apt-recommends disabled \
   --cache-stages "bootstrap rootfs" \
   --categories "main contrib non-free" \
   --distribution lenny \
   --hostname="amnesia" \
   --iso-application="Amnesia live system" \
   --iso-publisher="https://amnesia.boum.org/" \
   --iso-volume="Amnesia ${AMNESIA_FULL_VERSION}" \
   --memtest none \
   --username="amnesia" \
   --syslinux-timeout 4 \
   ${@}

# build i386 images on amd64 as well, include only 686 kernel
hw_arch="`dpkg --print-architecture`"
if [ "$hw_arch" = i386 -o "$hw_arch" = amd64 ]; then
   $RUN_LH_CONFIG \
      --architecture i386 \
      --linux-flavours 686 \
      ${@}
# build powerpc images on powerpc64 as well, include only powerpc kernel
elif [ "$hw_arch" = powerpc -o "$hw_arch" = powerpc64 ]; then
   $RUN_LH_CONFIG \
      --architecture powerpc \
      --linux-flavours powerpc \
      ${@}
fi

# locale-dependent configuration
. config/chroot
case "${LH_LANGUAGE}" in
   de)
      AMNESIA_APPEND="${AMNESIA_APPEND} locale=de_DE.UTF-8 keyb=de timezone=Europe/Berlin"
      ;;
   en)
      AMNESIA_APPEND="${AMNESIA_APPEND} locale=en_US.UTF-8 keyb=us timezone=America/Detroit"
      ;;
   fr)
      AMNESIA_APPEND="${AMNESIA_APPEND} locale=fr_FR.UTF-8 keyb=fr timezone=Europe/Paris"
      ;;
   *)
      ;;
esac
$RUN_LH_CONFIG --bootappend-live "${AMNESIA_APPEND}" ${@}

case "${LH_LANGUAGE}" in
   de|fr|en)
      PACKAGES_LISTS="standard amnesia-common amnesia-${AMNESIA_BASE} amnesia-${LH_LANGUAGE}"
      ;;
   *)
      PACKAGES_LISTS="standard amnesia-common amnesia-${AMNESIA_BASE}"
      ;;
esac
$RUN_LH_CONFIG --packages-lists="$PACKAGES_LISTS" ${@}

USERJS=config/chroot_local-includes/home/amnesia/.mozilla/firefox/hexybcy0.default/user.js
case "${LH_LANGUAGE}" in
   fr)
      echo 'user_pref("browser.search.defaultenginename", "Scroogle SSL French");' >> $USERJS
      echo 'user_pref("browser.search.selectedEngine", "Scroogle SSL French");' >> $USERJS
      ;;
   *)
      ;;
esac

# version
mkdir -p config/chroot_local-includes/etc/amnesia/
echo "${AMNESIA_FULL_VERSION}" > config/chroot_local-includes/etc/amnesia/version

# changelog
cp debian/changelog config/chroot_local-includes/usr/share/doc/amnesia/Changelog

# GnuPG key
cp wiki/src/amnesia.asc config/chroot_local-includes/usr/share/doc/amnesia/
