#! /bin/sh
# automatically run by lh_config

. config/amnesia
if [ -e config/amnesia.local ] ; then
   . config/amnesia.local
fi

RUN_LH_CONFIG="lh config noautoconfig"

# init config/ with defaults
$RUN_LH_CONFIG ${@}

# set Amnesia's general options
$RUN_LH_CONFIG \
   --apt-recommends disabled \
   --cache-stages "bootstrap rootfs" \
   --categories "main non-free" \
   --distribution lenny \
   --hostname="amnesia" \
   --iso-application="Amnesia live system" \
   --iso-publisher="https://amnesia.boum.org/" \
   --iso-volume="Amnesia ${AMNESIA_TODAY}" \
   --memtest none \
   --username="amnesia" \
   --syslinux-timeout 4 \
   ${@}

# build i386 images on amd64 as well,
# include only 686 kernel when building for i386
hw_arch="`dpkg --print-architecture`"
if [ "$hw_arch" = i386 -o "$hw_arch" = amd64 ]; then
   $RUN_LH_CONFIG \
      --architecture i386 \
      --linux-flavours 686 \
      ${@}
fi

# locale-dependent configuration
. config/chroot
case "${LH_LANGUAGE}" in
   de)
      AMNESIA_APPEND="${AMNESIA_APPEND} locale=de_DE.UTF-8 keyb=de timezone=Europe/Berlin"
      ;;
   fr)
      AMNESIA_APPEND="${AMNESIA_APPEND} locale=fr_FR.UTF-8 keyb=fr timezone=Europe/Paris"
      ;;
   *)
      ;;
esac
$RUN_LH_CONFIG --bootappend-live "${AMNESIA_APPEND}" ${@}

case "${LH_LANGUAGE}" in
   de|fr)
      PACKAGES_LISTS="standard amnesia-common amnesia-${AMNESIA_BASE} amnesia-${LH_LANGUAGE}"
      ;;
   *)
      PACKAGES_LISTS="standard amnesia-common amnesia-${AMNESIA_BASE}"
      ;;
esac
$RUN_LH_CONFIG --packages-lists="$PACKAGES_LISTS" ${@}

# version
mkdir -p config/chroot_local-includes/etc/amnesia/
echo "${AMNESIA_TODAY}" > config/chroot_local-includes/etc/amnesia/version

# changelog
cp debian/changelog config/chroot_local-includes/usr/share/doc/Changelog
