#!/usr/bin/ruby
#
# Usage:
#
#    apt-snapshots-serials-load-json SERIALS_JSON
#
# Example:
#
#    apt-snapshots-serials-load-json \
#      '{"torproject":"2017120803","debian-security":"2017120902","debian":"2017120903"}'

require 'json'

usage_str = "Usage: apt-snapshots-serials-load-json SERIALS_JSON"
ARGV.size == 1 or raise usage_str
serials = JSON.load(ARGV[0])

serials.each { |origin, serial|
  serial != 'latest' or raise "Only numeric serials are supported"
  puts "#{origin}: #{serial}\n"
}
