#!/bin/sh
set -e
set -u

BASE_URL=http://time-based.snapshots.deb.tails.boum.org/
CONFIG=config/APT_snapshots.d
ORIGINS=$(cd $CONFIG; ls -d *)

get_serial() {
	origin=$1
	wget -q $BASE_URL/$origin/project/trace/$origin -O -|awk -F': ' '/^Archive serial: / {print $2}'
}

action="$1"
case "$action" in
	info)
		for origin in $ORIGINS; do
			online=$(get_serial $origin)
			echo "$origin: $online"
		done
	;;
	freeze)
		for origin in $ORIGINS; do
			serial_file="$CONFIG/$origin/serial"
			git=$(cat $serial_file)
			online=$(get_serial $origin)
			printf "Origin $origin:\n  old: $git\n  new: $online\n"
			echo $online > $serial_file
		done
		printf "\nAll files ($CONFIG/*/serial) have been updated with new serials\n" >&2
	;;
	prepare-build)
		cp -r config/APT_snapshots.d tmp
		$0 info > tmp/cached_APT_snapshots_serials
		for origin_dir in tmp/APT_snapshots.d/*; do
			origin=$(basename $origin_dir)
			if grep -qs '^latest$' $origin_dir/serial; then
				awk -F': ' "/^$origin: / {print \$2}" tmp/cached_APT_snapshots_serials > $origin_dir/serial
			fi
		done
	;;
	*)
		printf "unknown action ($action), use either 'info' or 'freeze'\n" >&2
		exit 1
	;;
esac
