#!/bin/sh

PREREQ=""

# Duplicated in features/step_definitions/erase_memory.rb
KERNEL_MEM_RESERVED_K=$((64*1024))
ADMIN_MEM_RESERVED_K=$((128*1024))

prereqs() {
   echo "${PREREQ}"
}

tweak_sysctl() {
   echo 3   > /proc/sys/kernel/printk

   echo 3   > /proc/sys/vm/drop_caches

   echo 0   > /proc/sys/vm/overcommit_memory
   echo 0   > /proc/sys/vm/oom_kill_allocating_task
   echo 0   > /proc/sys/vm/oom_dump_tasks

   if [ "${sdmemdebug}" = 1 ] ; then
    # Make sure the kernel doesn't starve, for better reliability when
    # running the test suite.
    echo "$KERNEL_MEM_RESERVED_K" > /proc/sys/vm/min_free_kbytes
    echo "$ADMIN_MEM_RESERVED_K"  > /proc/sys/vm/admin_reserve_kbytes
   fi
}

case ${1} in
   prereqs)
      prereqs
      exit 0
      ;;
esac

if [ -n "${sdmem}" ] ; then
   tweak_sysctl
   if [ -z "${sdmemopts}" ] ; then
      sdmemopts="v"
   fi
   /usr/bin/sdmem "-${sdmemopts}"
   echo "Memory has been wiped!"
fi

if [ "${sdmemdebug}" = 1 ] ; then
   clear
   echo "Going to sleep 10 minutes. Happy dumping!"
   sleep 1200
fi

case "${sdmem}" in
   halt)
      echo "Powering off..."
      /sbin/poweroff -fd
      ;;
   reboot)
      echo "Restarting..."
      /sbin/reboot -fd
      ;;
   *)
      ;;
esac
