#!/bin/sh

PREREQ=""

prereqs() {
   echo "${PREREQ}"
}

tweak_sysctl() {
   echo 3   > /proc/sys/kernel/printk

   echo 3   > /proc/sys/vm/drop_caches

   echo 0   > /proc/sys/vm/overcommit_memory
   echo 0   > /proc/sys/vm/oom_kill_allocating_task
   echo 0   > /proc/sys/vm/oom_dump_tasks
}

case ${1} in
   prereqs)
      prereqs
      exit 0
      ;;
esac

if [ -n "${sdmem}" ] ; then
   tweak_sysctl
   if [ -z "${sdmemopts}" ] ; then
      sdmemopts="v"
   fi
   /usr/bin/sdmem "-${sdmemopts}"
fi

if [ "${sdmemdebug}" = 1 ] ; then
   clear
   echo "Going to sleep 10 minutes. Happy dumping!"
   sleep 600
fi

case "${sdmem}" in
   halt)
      /sbin/poweroff -fd
      ;;
   reboot)
      /sbin/reboot -fd
      ;;
   *)
      ;;
esac
