# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1221827973);
user_pref("app.update.lastUpdateTime.background-update-timer", 1221827971);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1221827973);
user_pref("extensions.enigmail.allowEmptySubject", true);
user_pref("extensions.enigmail.configuredVersion", "0.95.0");
user_pref("extensions.enigmail.confirmBeforeSend", true);
user_pref("extensions.enigmail.useDefaultComment", true);
user_pref("extensions.lastAppVersion", "2.0.0.19");
user_pref("extensions.update.notifyUser", false);
user_pref("mail.attachment.store.version", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.smtpservers", "");
user_pref("mail.spam.version", 1);
user_pref("mailnews.headers.extraExpandedHeaders", "x-enigmail-version content-transfer-encoding openpgp x-mimeole x-bugzilla-reason x-php-bug");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.ui.threadpane.version", 5);
