#!/bin/sh

# Configure IBus with sensible settings for use in Tails,
# and with the correct default engine for the user's login locale.

# The IBus engine is only started if required by the login locale,
# as it is known to interfer with keyboard shortcuts in some locales.

# The environment variables are exported however, so the user can
# start IBus manually using the launcher "IBus Preferences"
# in the System->Preferences menu.

# XXX: This script may not be needed anymore when Tails
# is based on GNOME 3.6 or newer (which is in Debian Jessie).
# https://help.gnome.org/misc/release-notes/3.6/i18n-ibus.html


# Deside order in which input methods are preferred
# (chinese needs pinyin, japanese needs anthy, korean needs hangul,
# vietnamese needs Unikey)
# (bopomofo is an alternative input method for chinese)
LANGPREFIX=`echo "$LANG" | sed 's/_.*//'`
PREFLIST='[pinyin,anthy,hangul,Unikey,bopomofo]'
NEEDIBUS='n'

case "$LANGPREFIX" in
   ja)
      PREFLIST='[anthy,pinyin,hangul,Unikey,bopomofo]'
      NEEDIBUS='y'
      ;;
   ko)
      PREFLIST='[hangul,pinyin,anthy,Unikey,bopomofo]'
      NEEDIBUS='y'
      ;;
   vi)
      PREFLIST='[Unikey,pinyin,anthy,hangul,bopomofo]'
      NEEDIBUS='y'
      ;;
   zh)
      PREFLIST='[pinyin,bopomofo,anthy,hangul,Unikey]'
      NEEDIBUS='y'
      ;;
esac

# Configure enabled input methods and their preferred order
gconftool-2 --type=list --list-type=string --set \
   /desktop/ibus/general/preload_engines "$PREFLIST"

# Export environment variables to enable use of IBus
export GTK_IM_MODULE='ibus'
export QT_IM_MODULE='ibus'
export XMODIFIERS='@im=ibus'

# Start the IBus input method daemon, if required by locale
if [ "$NEEDIBUS" = 'y' ]; then
   /usr/bin/ibus-daemon --daemonize --xim
fi
