#!/bin/sh

set -e

ARGS=
if grep -qw bridge /proc/cmdline; then
   ARGS='-bridgeconf'
fi


# Get LIVE_USERNAME
. /etc/live/config.d/username.conf

# Get LANG
. /etc/default/locale

if killall vidalia 2> /dev/null; then
   sleep 2 # give lckdo a chance to release the lockfile
fi

until pgrep -u "${LIVE_USERNAME}" nm-applet >/dev/null ; do
   sleep 5
done

export LANG
export DISPLAY=':0.0'
export XAUTHORITY="`echo /var/run/gdm3/auth-for-${LIVE_USERNAME}-*/database`"

sudo -u ${LIVE_USERNAME} xhost +SI:localuser:vidalia
sudo -u vidalia lckdo /var/lock/vidalia vidalia -DISPLAY=${DISPLAY} ${ARGS} &
until pgrep -u vidalia vidalia >/dev/null ; do
   sleep 5
done
sudo -u ${LIVE_USERNAME} xhost -SI:localuser:vidalia
