#!/bin/sh

set -e

# Import export_gnome_env().
. /usr/local/lib/tails-shell-library/gnome.sh

# Get LIVE_USERNAME
. /etc/live/config.d/username.conf

# Get LANG
. /etc/default/locale

for i in $(seq 10); do
   killall -SIGKILL vidalia || :
   sleep 1
   if ! pgrep "^vidalia$"; then
      break
   fi
done

until pgrep -u "${LIVE_USERNAME}" "^ibus-daemon" >/dev/null ; do
   sleep 5
done

export LANG
export_gnome_env

(
sudo -u ${LIVE_USERNAME} xhost +SI:localuser:vidalia
sudo -u vidalia lckdo /var/lock/vidalia vidalia -DISPLAY=${DISPLAY}
sudo -u ${LIVE_USERNAME} xhost -SI:localuser:vidalia
) &
