#!/bin/sh

set -e

# Get LIVE_USERNAME
. /etc/live/config.d/username.conf

# Get LANG
. /etc/default/locale

# Get windows_camouflage_is_enabled
. /usr/local/lib/tails-shell-library/tails-greeter.sh

for i in $(seq 10); do
   killall -SIGKILL vidalia || :
   sleep 1
   if ! pgrep "^vidalia$"; then
      break
   fi
done

# We don't want to start Vidalia if Windows Camouflage is enabled (ticket #7400)
windows_camouflage_is_enabled && exit 0

until pgrep -u "${LIVE_USERNAME}" "^nm-applet$" >/dev/null ; do
   sleep 5
done

export LANG
export DISPLAY=':0.0'
export XAUTHORITY="`echo /var/run/gdm3/auth-for-${LIVE_USERNAME}-*/database`"

(
sudo -u ${LIVE_USERNAME} xhost +SI:localuser:vidalia
sudo -u vidalia lckdo /var/lock/vidalia vidalia -DISPLAY=${DISPLAY}
sudo -u ${LIVE_USERNAME} xhost -SI:localuser:vidalia
) &
