#! /bin/sh

# This script is meant to be run by TailsGreeter
# It reads /var/lib/gdm3/tails.locale for locale name
# and /var/lib/gdm3/tails.password for the password which is stored in
# the $TAILS_USER_PASSWORD variable.

if [ -z "${TAILS_USER_PASSWORD}" ] ; then
    exit 0
fi

# For whatever reason, /usr/sbin (needed by at least chpasswd and
# adduser) is not in our environment
export PATH="/usr/sbin:${PATH}"

# Import the name of the live user
. /etc/live/config.d/username || exit 1
if [ -z "${LIVE_USERNAME}" ] ; then
    exit 2
fi

# Sets the password
echo "${LIVE_USERNAME}:${TAILS_USER_PASSWORD}" | chpasswd

# Makes the user sudoer and considered as admin for policykit
adduser "${LIVE_USERNAME}" sudo

# Configure su-to-root to use sudo
sudo -u "${LIVE_USERNAME}" sh -c "echo 'SU_TO_ROOT_SU=sudo' >> /home/${LIVE_USERNAME}/.su-to-rootrc"

# Configure gksu to use sudo
if [ -x /usr/bin/gconftool-2 ]
then
    sudo -u "${LIVE_USERNAME}" gconftool-2 -s -t bool /apps/gksu/sudo-mode true
fi
