#!/bin/sh

debug_command() {
    echo
    echo "===== output of command $@ ====="
    "$@"
}

debug_file() {
    local user="${1}"
    shift
    file="${1}"
    [ ! -e "${file}" ] && return
    echo
    echo "===== content of $1 ====="
    sudo -u "${user}" -- cat "${file}"
}

debug_command /usr/sbin/dmidecode -s system-manufacturer
debug_command /usr/sbin/dmidecode -s system-product-name
debug_command /usr/sbin/dmidecode -s system-version
debug_command "/bin/dmesg"
debug_command "/bin/lsmod"
debug_command "/bin/mount"
debug_command "/usr/bin/lspci"
debug_command grep spoof-mac: /var/log/messages

debug_file root "/etc/X11/xorg.conf"
debug_file amnesia "/home/amnesia/.xsession-errors"
debug_file root "/proc/asound/cards"
debug_file root "/proc/asound/devices"
debug_file root "/proc/asound/modules"
debug_file root "/var/log/Xorg.0.log"
debug_file Debian-gdm "/var/log/gdm3/:0-slave.log"
debug_file Debian-gdm "/var/log/gdm3/:0-greeter.log"
debug_file Debian-gdm "/var/log/gdm3/tails-greeter.errors"
debug_file root "/var/log/live-persist"
debug_file root "/var/log/live/boot.log"
debug_file root "/var/log/live/config.log"
debug_file root "/var/lib/gdm3/tails.persistence"
debug_file root "/var/lib/live/config/tails.physical_security"
debug_file root "/live/persistence/TailsData_unlocked/persistence.conf"
debug_file root "/live/persistence/TailsData_unlocked/live-additional-software.conf"
