#!/bin/sh

set -e

. /usr/local/lib/tails-shell-library/log.sh
set_log_tag unblock-network

BLACKLIST=/etc/modprobe.d/all-net-blacklist.conf

rm -f "${BLACKLIST}" || true
/sbin/udevadm trigger --action=add

# Make this script block until all triggers have been run. We normally
# start NetworkManager immediately after this script, and without the
# blocking behaviour there's a race between NM and the MAC spoof udev
# triggers. When NM takes control of some network device, some
# operations are not possible on the device, like MAC spoofing. Hence,
# if NM wins, the udev trigger's run of tails-spoof-mac will fail.
/sbin/udevadm settle

if [ -e "${BLACKLIST}" ]; then
    log "${BLACKLIST} wasn't removed so the network will still be blocked"
fi
