#!/bin/sh

set -e

# Import export_gnome_env().
. /usr/local/lib/tails-shell-library/gnome.sh

# Get LIVE_USERNAME
. /etc/live/config.d/username.conf

# Get LANG
. /etc/default/locale

until pgrep -u "${LIVE_USERNAME}" '^ibus-daemon' >/dev/null ; do
   sleep 5
done

export LANG
export_gnome_env
exec tca
