#!/usr/bin/python3

import sys

from tailslib.additionalsoftware.config import (
    remove_additional_packages,
    get_additional_packages)

if len(sys.argv) != 2:
    sys.exit(2)

old_package = str(sys.argv[1])

additional_packages = get_additional_packages(search_new_persistence=True)
if old_package in additional_packages:
    remove_additional_packages({old_package}, search_new_persistence=True)
else:
    sys.exit(1)
