#!/bin/sh

# The desktop user is allowed to do so with passwordless sudo.

/bin/systemctl --quiet is-active tor.service || exit 1
[ 'inactive' \
      = \
      $(/bin/systemctl is-active \
		       tails-wait-until-tor-has-bootstrapped.service || :) \
]
