#!/bin/sh

ID=/dev/block/`/bin/mountpoint -d /live/image`
DEVICE=`/sbin/udevadm info -q path -p  "${ID}"`
DEV_TYPE=`/sbin/udevadm info -q property -p "${ID}" | /bin/grep ID_TYPE | /usr/bin/awk -F "=" '{ print $2 }'`


# First clean the screen, then brutally shutdown the machine.
do_stop() {
	/etc/init.d/gdm3 stop 2>&1 >/dev/null
	/etc/init.d/kexec-load stop 2>&1 >/dev/null
	/etc/init.d/tails-kexec stop 2>&1 >/dev/null
}

# Let's be sure the CDRom can be ejected by pressing the button
if [ $DEV_TYPE = "cd" ]; then
	/usr/bin/eject -i off "${ID}" 2>&1 >/dev/null
fi


# Cache the necessary files to quickly shutdown.
/etc/init.d/tails-kexec-cache stop 2>&1 >/dev/null

# Start udev-watchdog and stop on clean exit.
/usr/local/sbin/udev-watchdog "$DEVICE" "$DEV_TYPE" && do_stop
